### ISSUE TITLE
Syncing data from the cloud server if the app data is lost

### ISSUE THREAD

**Issue by amalafrozalam** [Intelehealth/Android-Mobile-Client#207]
Everything, should always be on the tablet, for all patients that have the prefix of that tablet. So if the prefix of the tablet if KEF, then all patients that have the prefix KEF should be downloaded and stored on the tablet. 

This still is wonky, because it's related to #201. OpenMRS is not returning patients when searched by prefix.

**Comment by nehagoel2** [comment]
Currently fixed by #329 by taking a local backup of the device's database on the device itself. There are several challenges with backing up from the OpenMRS cloud instance.
