### ISSUE TITLE
Patient Detail screen should have an edit button too

### ISSUE THREAD

**Issue by amalafrozalam** [Intelehealth/Android-Mobile-Client#213]
The patient details should be allowed to be edited. Should be manual edit that goes back to the identification screen where you can edit things. Then when you go back to patient detail screen, shoot off a service that updates the patient's information on OpenMRS, using the same UUID as before.

**Comment by nehagoel2** [comment]
You should also be able to edit the following information on the patient detail screen:
1. Patient information --- go back to the identification screen
2. History card --- shortcut is to use the same fix as on the Visit Summary screen (edit text, erase and redo, cancel)

![image](https://user-images.githubusercontent.com/14187848/27221327-d68cae6c-52a5-11e7-9412-db46de4c1393.png)

**Comment by nehagoel2** [comment]
Easiest fix - replace the History card on this screen with the two Past Medical History and Family History cards on the Visit Summary Screen!
