### ISSUE TITLE
App needs to update from non-Google Play store

### ISSUE THREAD

**Issue by amalafrozalam** [Intelehealth/Android-Mobile-Client#216]
For the time being, the app needs to update from a separate site. Each client will essentially have a folder/repo where their apps will check for new versions and download newer versions if needed. These new versions will be for updated mind maps.

NOTE: might need different package name? Doubt it.

**Comment by nehagoel2** [comment]
Since we have been able to set up a system for updating via playstore...we need to actually figure out a way to allow for set up level changes so that updates are pushed via playstore
