### ISSUE TITLE
Upload services should all be visible

### ISSUE THREAD

**Issue by amalafrozalam** [Intelehealth/Android-Mobile-Client#225]
The CHW should be able to see what has been uploaded and what is waiting to be uploaded.

**Comment by nehagoel2** [comment]
See the CommCare app with how they show the upload status of their forms.

**Comment by nehagoel2** [comment]
Partially complete - in progress upload notification is still left

**Comment by prithi69** [comment]
Image upload : Visit image  (visible)
Pateint data upload : visible
Visit data upload  : visible 
prescription download : visible

**Comment by amalafrozalam** [comment]
Linked to #334
