### ISSUE TITLE
PatHistory and FamHistory should be skipped for returning patients

### ISSUE THREAD

**Issue by amalafrozalam** [Intelehealth/Android-Mobile-Client#234]

**Comment by nehagoel2** [comment]
Move the Past Medical History and Family History screen from the New Visit Workflow to the New Patient Workflow.

**Comment by nehagoel2** [comment]
Modified Workflow for new patient: IdentificationActivity--PastHistory--FamilyHistory--PatientDetail

Modified Workflow for new visit: PatientDetail--ComplaintSelect--QuestionNode--PhysicalExam--Vitals--VisitSummary
