### ISSUE TITLE
Move from Acra to firebase for crash analytics

### ISSUE THREAD

**Issue by amalafrozalam** [Intelehealth/Android-Mobile-Client#243]
Create firebase events tracking

**Comment by amalafrozalam** [comment]
https://www.toptal.com/android/automated-android-crash-reports-with-acra-and-cloudant

**Comment by AniketIntelhealth** [comment]
1.Generated googleservices.json file by using credentials for login id of support@intelehealth.io
2.this json file added to the app folder.
3.added required dependencies of firebase .
Note:In console of firebase the project name for crash reporting is "intelehealthCrashlytics"

**Comment by AniketIntelhealth** [comment]
/*=====================Firebase Push Notification====================*/

1. Created a variable called token_id and added to the database in identificationActivity.class
    this token_id stores value of token for each unique device.
2. This token_id is send to openmrs via uuid
3. Below code generates the token for each device in MyFirebaseInstanceIdServices.class


    @Override
    public void onTokenRefresh() {

        //Getting registration token
        String refreshedToken = FirebaseInstanceId.getInstance().getToken();

        //Displaying token on logcat
        Log.d(TAG, "Refreshed token: " + refreshedToken);
//        insertToken(refreshedToken);
    }
