### ISSUE TITLE
Remove all hard-coded concepts in the app

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#275]
This may involve creating new concept tables in the app's db and "getting" the concept dictionary from OpenMRS at setup.

**Comment by nehagoel2** [comment]
@amalafrozalam - Where all have we put in hard-coded concepts????

**Comment by amalafrozalam** [comment]
@nehagoel2 which concepts are you referring to? The ones for physical exam and such, or for each specific node?
