### ISSUE TITLE
Input-type questions should erase any previous responses

### ISSUE THREAD

**Issue by amalafrozalam** [Intelehealth/Android-Mobile-Client#327]
When a user clicks on a node with an input-type, the response is then added to the language attribute of the node. Then, the node's text is updated to match that, for readability purposes. If the user clicks the node again, the new input is now appended to the node language, instead of being replaced.

Example:
Node input-type is "Duration"
Language is "Since when: _ ago"
User clicks on node, selects 2 weeks
Node updates to display "Since when: 2 weeks ago"
User clicks on node again, selects 5 weeks
Node updates to display "Since when: 2 weeks ago 5 weeks"
This also changes what is ultimately stored in the database, and the final version is what is stored.

This should change to erase previous entries, if new entries are input.

**Comment by nehagoel2** [comment]
Can we bump this up the priority list? Its a major UI/UX issue.

**Comment by amalafrozalam** [comment]
Solution this is in #387, which is also a duplicate of this issue.
