### ISSUE TITLE
Switch the identifier from OpenMRS ID to OpenMRS Identification number

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#331]
Current identifier:
OpenMRS ID
Desc: OpenMRS patient identifier, without check digit
uuid: 05a29f94-c0ed-11e2-94be-8c13b969e334

Identifier we should use:
OpenMRS Identification Number
Desc: Unique number used in OpenMRS
uuid: 8d793bee-c2cc-11de-8d13-0010c6dffd0f

**Comment by amalafrozalam** [comment]
@dbarretto please test this
