### ISSUE TITLE
App posts multiple persons and patients for the same record

### ISSUE THREAD

**Issue by prithi69** [Intelehealth/Android-Mobile-Client#333]
There is no pattern to this, it is very inconsistent.

eg: 

1. Sanjeeda Khopre - 4 persons and 2 patients were created for this record.

mysql> select * from person_name where given_name ='Sanjeeda';
+----------------+-----------+-----------+--------+------------+-------------+--------------------+-------------+--------------+--------------------+--------+---------+---------------------+--------+-----------+---------------------+--------------+------------+---------------------+--------------------------------------+
| person_name_id | preferred | person_id | prefix | given_name | middle_name | family_name_prefix | family_name | family_name2 | family_name_suffix | degree | creator | date_created        | voided | voided_by | date_voided         | void_reason  | changed_by | date_changed        | uuid                                 |
+----------------+-----------+-----------+--------+------------+-------------+--------------------+-------------+--------------+--------------------+--------+---------+---------------------+--------+-----------+---------------------+--------------+------------+---------------------+--------------------------------------+
|            247 |         1 |       246 | NULL   | Sanjeeda   | NULL        | NULL               | Khopre      | NULL         | NULL               | NULL   |       4 | 2017-08-12 10:19:43 |      1 |         1 | 2017-08-12 10:26:40 | demo patient |          1 | 2017-08-12 10:26:40 | e1f444a3-fe93-42ad-8c46-e12075c4f8d4 |
|            248 |         1 |       247 | NULL   | Sanjeeda   | NULL        | NULL               | Khopre      | NULL         | NULL               | NULL   |       4 | 2017-08-12 10:20:17 |      0 |      NULL | NULL                | NULL         |       NULL | NULL                | c6faa85e-8e9b-4621-9a20-cacc33ff6a0d |
|            249 |         1 |       248 | NULL   | Sanjeeda   | NULL        | NULL               | Khopre      | NULL         | NULL               | NULL   |       4 | 2017-08-12 10:23:58 |      0 |      NULL | NULL                | NULL         |       NULL | NULL                | 96c862d2-2194-42f0-872f-a20bb66125a7 |
|            250 |         1 |       249 | NULL   | Sanjeeda   | NULL        | NULL               | Khopre      | NULL         | NULL               | NULL   |       4 | 2017-08-12 10:25:20 |      0 |      NULL | NULL                | NULL         |       NULL | NULL                | 333026ec-45a6-4d56-8c65-e042ed557346 |
|            251 |         1 |       250 | NULL   | Sanjeeda   | NULL        | NULL               | Khopre      | NULL         | NULL               | NULL   |       4 | 2017-08-12 11:04:05 |      0 |      NULL | NULL                | NULL         |          4 | 2017-08-12 11:04:05 | cef1ddc0-8135-4025-a7c6-c86f941595dd |
+----------------+-----------+-----------+--------+------------+-------------+--------------------+-------------+--------------+--------------------+--------+---------+---------------------+--------+-----------+---------------------+--------------+------------+---------------------+--------------------------------------+
5 rows in set (0.00 sec)

mysql> select * from patient where patient_id='247' OR patient_id='248' OR patient_id='249' OR patient_id='250' OR patient_id='251';
+------------+---------+---------------------+------------+---------------------+--------+-----------+-------------+-------------+----------------+
| patient_id | creator | date_created        | changed_by | date_changed        | voided | voided_by | date_voided | void_reason | allergy_status |
+------------+---------+---------------------+------------+---------------------+--------+-----------+-------------+-------------+----------------+
|        250 |       4 | 2017-08-12 11:04:05 |          4 | 2017-08-12 11:04:05 |      0 |      NULL | NULL        | NULL        | Unknown        |
|        251 |       4 | 2017-08-12 12:03:34 |          4 | 2017-08-12 12:03:34 |      0 |      NULL | NULL        | NULL        | Unknown        |
+------------+---------+---------------------+------------+---------------------+--------+-----------+-------------+-------------+----------------+
2 rows in set (0.00 sec)

==================

2. Shanti Devi - two persons and one patient was created for this record.
mysql> select * from person_name where given_name ='Shanti';
+----------------+-----------+-----------+--------+------------+-------------+--------------------+-------------+--------------+--------------------+--------+---------+---------------------+--------+-----------+-------------+-------------+------------+---------------------+--------------------------------------+
| person_name_id | preferred | person_id | prefix | given_name | middle_name | family_name_prefix | family_name | family_name2 | family_name_suffix | degree | creator | date_created        | voided | voided_by | date_voided | void_reason | changed_by | date_changed        | uuid                                 |
+----------------+-----------+-----------+--------+------------+-------------+--------------------+-------------+--------------+--------------------+--------+---------+---------------------+--------+-----------+-------------+-------------+------------+---------------------+--------------------------------------+
|            254 |         1 |       253 | NULL   | Shanti     | NULL        | NULL               | Devi        | NULL         | NULL               | NULL   |       4 | 2017-08-12 12:54:37 |      0 |      NULL | NULL        | NULL        |          4 | 2017-08-12 12:54:37 | 8f2cf4a8-358d-4859-86a1-b3dd540f1a5e |
|            255 |         1 |       254 | NULL   | Shanti     | NULL        | NULL               | Devi        | NULL         | NULL               | NULL   |       4 | 2017-08-12 12:55:03 |      0 |      NULL | NULL        | NULL        |       NULL | NULL                | 9630fb8f-5954-4e49-a188-35c67191cd2f |
+----------------+-----------+-----------+--------+------------+-------------+--------------------+-------------+--------------+--------------------+--------+---------+---------------------+--------+-----------+-------------+-------------+------------+---------------------+--------------------------------------+
2 rows in set (0.00 sec)

mysql> select * from patient where patient_id='254' or patient_id='255';
+------------+---------+---------------------+------------+---------------------+--------+-----------+-------------+-------------+----------------+
| patient_id | creator | date_created        | changed_by | date_changed        | voided | voided_by | date_voided | void_reason | allergy_status |
+------------+---------+---------------------+------------+---------------------+--------+-----------+-------------+-------------+----------------+
|        255 |       4 | 2017-08-14 12:19:07 |          4 | 2017-08-14 12:19:08 |      0 |      NULL | NULL        | NULL        | Unknown        |
+------------+---------+---------------------+------------+---------------------+--------+-----------+-------------+-------------+----------------+
1 row in set (0.00 sec)

**Comment by prithi69** [comment]
Multiple person_id is being created of a same patient if we update the patient details ,

**Comment by amalafrozalam** [comment]
@prithi69 wait, as this issue from like months ago is still happening?

**Comment by prithi69** [comment]
This issue was solved by Dexter, and this issue was solved on our first play store release 1.0

**Comment by nehav39** [comment]
Branch: reverted-back (taken care of by Sync)
