### ISSUE TITLE
IF we dont save the picture which we clicked for SCAR physical Examintation, its still visible in the Visit Summary of the app.

### ISSUE THREAD

**Issue by prithi69** [Intelehealth/Android-Mobile-Client#336]
If we click the wrong picture of the scar physical Examination and don't save it (i.e. select DELETE), and clicked the right picture. In the visit summary screen right picture and also the wrong picture showed up, wrong picture should not be shown up as we haven't saved it.

**Comment by nehagoel2** [comment]
Minor change - on press of DELETE, reopen camera
