### ISSUE TITLE
Make the Sync screen more user friendly

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/Android-Mobile-Client#338]

**Comment by amalafrozalam** [comment]
I'll design the screen, and then hand off development to someone else depending on time.

**Comment by nehagoel2** [comment]
@amalafrozalam - If this screen isn't ready can we hide it from the user for now and only introduce it once its ready?

**Comment by amalafrozalam** [comment]
Yeah that's probably a good idea. This got moved off my table. I might get a chance this week.
