### ISSUE TITLE
Internet connectivity indicator on Visit Summary screen should turn ON over a certain b/w threshold

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#344]
The indicator should have three states:
1. Internet connection is sufficient to upload data and photos
2. Internet connection is sufficient to upload data but not photos
3. Internet connection weak, can't upload anything

Right now, the indicator turns green when there is an internet connection, but even when its too weak.

Need to change the indicator from a green circle to some other UI element. Its too visually similar to active visit and completed visit indicators in the today's patient's screen.

**Comment by nehagoel2** [comment]
User need:
Health worker needs to know the status of data upload (for text and images)
Since the major cause of data not getting uploaded is no/poor data connectivity, the CHW needs to know what they need to do in order to allow data upload (move to an area of better connectivity, turn OFF/ON mobile data, etc.)

**Comment by nehagoel2** [comment]
Text: 25-30 (10-12 kbps)
Images: 60-70 kbps (25-30 kbps)

**Comment by nehagoel2** [comment]
How does this relate to H/E/2G/3G?

**Comment by prithi69** [comment]
There are many symbols of the internet connection which we see in our mobile. like G,E, 2G,3G,,H,H+,4G,
**So G stands for GPRS (General Packet Radio Service).** It indicates the slowest speed of internet data transfer in your mobile phone. When you see G near your signal strength indicator, it is certain that your net connection is working at the slowest speed.

**GPRS is considered to be the second generation (2G) mobile technology**. It is the slowest and oldest among all mobile tecnologies. It is mainly good enough for sending text messsges using apps like WhatsApp. Data rates in GPRS  whose maximum speed is 56kbps
**Letter E stands for EDGE (Enhanced Data Rates for GSM Evolution**). It is also called Enhanced GPRS. This technology lies somewhere in between 2G and 3G technology. So, some people refer to it as 2.5G.

**EDGE is faster that GPRS but still not good enough to browse the internet. I**t takes lot of time in loading websites when your signal bar is showing E letter alongside. Typically EDGE provides a data rate of  60 kbps u in ideal conditions data rate of up to 1 Mbps can also be achieved. This technology also lies somewhere in between 2G and 3G. Those who call GPRS as 2.5 G, they refer EDGE as 2.75G.

3G means the third generation of mobile telephone technology. It uses the Universal Mobile Telecommunication Sytsem and is based on GSM Standards.

Typically 3g provides data transfer rates 384 kbit/second. But depending upon how it is implemented on various networks, the date rate can go up to 42 Mbits/second.

Usually 3G is faster than EDGE and you can easily browse websites and stream music.

H stands for HSPA (High-speed Packet Access). It is an enhanced form of 3G technology. HSPA provides higher data transfer rates than the basic 3G. HSPA can provide peak data rates of up to 14 Mbit/s for downlink and 5.76 Mbit/s for up uplink.

High-Speed Downlink Packet Access (HSDPA) is a further enhanced version of HSPA. HSDPA supports download speed of up to 99.3 Mbit/s.

When you see letter H near the signal bar in your mobile phone, you can stream music and even Youtube Videos without much interruption.

So here is the brief introduction about the relation of G./E/2G/3G/H.
As text data of our app uploads 25 to 30kbps of data which falls on a 2G category as its maximum speed is 56kbps.

And  Image of our app uploads 50 to 70kbps minimum, so we can say that the image will get uploaded if there is E signal in the phone atleast, which is a Edge technology

This is how it relates.

**Comment by nehagoel2** [comment]
I might suggest dropping the internet connectivity indicator in this release and adding this feature later

**Comment by amalafrozalam** [comment]
Linked to #338
