### ISSUE TITLE
data not getting uploaded or downloaded in various scenarios

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#349]
this could be because of :
1. Network connectivity is poor - bandwidth is too low for data upload (need to know below what bandwidth threshold data upload cannot occur)
2. packet loss during data transmission causing a 400 error on openmrs side
3. 400 error due to some unknown problem on openmrs rest api module
4. 400 error due to multiple spaces in mind map
5. Device hardware issue - radio in moto e4 plus not optimal in low bandwidth
6. Device software issue - /nougat not optimized for low bandwidth
7. App services not optimized

**Comment by nehagoel2** [comment]
400 error - bad request
500 error - internal server error (stacktrace available in tomcat server logs)

**Comment by nehagoel2** [comment]
services in order of payload size:
1. Image upload
2. Prescription download
3. Visit Upload
4. Patient upload
5. Setup
6. Login

**Comment by prithi69** [comment]
This was working in OTG testing and its also working in latest apk.

**Comment by nehagoel2** [comment]
Since this is working I have closed the issue, we can reopen it if we see this happening a lot.
