### ISSUE TITLE
Confirmation dialog for each complaint should verify if correct information is used

### ISSUE THREAD

**Issue by amalafrozalam** [Intelehealth/Android-Mobile-Client#359]
There is currently a confirmation dialog at the end of each complaint to simply verify if the user has answered all the questions that they can. This should change.

Instead, the dialog box should present the CHW with the questions that they answered and the answers they selected. In other words, it should be formatted like this:

**Duration**
- 5 hours
**When did it start?**
- Yesterday

The dialog box text should be formatted in a "bullet" format. The buttons should read "keep editing" or "looks good." All of this should be in the language that the app is currently in (as of this issue, the language is based on the system language).

**Comment by amalafrozalam** [comment]
It should also say at the bottom at that they didn't answer.

**Comment by dbarretto** [comment]
<img width="354" alt="screen shot 2017-12-01 at 19 07 40" src="https://user-images.githubusercontent.com/28301176/33485226-9bf67f6c-d6cb-11e7-8a8a-6763e84ffd6e.png">
This is how it looks currently. I added round bullets instead of tab because if text overflows to the next line then it look ugly. This looks better!

**Comment by amalafrozalam** [comment]
@dbarretto can you do indentation? 

After the questions that they answered, add a section that says "Questions not answered"
This should just be a list of the questions they did not answer.

The buttons should be "Keep editing" and "looks good"

**Comment by nehagoel2** [comment]
Can we use icons instead of text on the buttons?
Pencil = keep editing
Check mark = looks good.

The healthworkers learn better with visual symbols

**Comment by dbarretto** [comment]
@amalafrozalam : Indentation is not possible... if text is long then it overflows to the next line and then it look super ugly and confusing

**Comment by dbarretto** [comment]
@amalafrozalam : I'll add the Questions not answered section...

**Comment by dbarretto** [comment]
@nehagoel2 : Do you need the Questions not answered section only for first level node or for all nodes?

**Comment by nehagoel2** [comment]
Please forget the questions not answered part. It's a nice to have feature. Only need to have features in this release. We can move that to 1.1

**Comment by amalafrozalam** [comment]
@dbarretto Create a new issue for questions not answered. Leave this and commit the code.

**Comment by dbarretto** [comment]
@amalafrozalam The code is already committed.. on branch 372

**Comment by nehagoel2** [comment]
See #381
