### ISSUE TITLE
Images from app not being displayed in OpenMRS

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#369]
This could be because:

1. They weren't posted to Parse
2. They weren't displayed on OpenMRS

[See patient Infect, 34]

**Comment by prithi69** [comment]
apps is posting images on parse server and we verified it in parse dashboard.

**Comment by prithi69** [comment]
Its being displayed in the OpenMRS, tested on both test and production server.
