### ISSUE TITLE
Punctuation not perfect.

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#371]

**Comment by nehagoel2** [comment]
Current note sample:

Abdominal Pain: Site - Upper (R) - Right Hypochondrium. Radiation - Pain radiates to - Right shoulder. Duration - since  1 Weeks. Character of the pain - Constant, Dull, aching. Severity - Severe, 7-9. ,  Vomiting,  Fever,  Decrease in appetite,    chills chills, headache chills, headache, body ache chills , headache, body ache, dry cough,  Nausea,  Anorexia,  Diarrhoea,  Constipation,  Abdominal distention / Bloating,  Belching / Burping,  Flatulence,  Color change in stool [describe],  Blood in stool,  Change in frequency of urinating [describe],  Color change in urine [describe],  Hiccups,  Restlessness,  Injury - Exacerbating Factors - Coughing,  resting on right side. Relieving Factors - None/Denied

**Comment by nehagoel2** [comment]
Desired note:

Abdominal Pain: 
- Site Upper (R) - Right Hypochondrium. 
- Radiation - Pain radiates to - Right shoulder. 
- Duration - since  1 Weeks. 
- Character of the pain - Constant, Dull, aching. 
- Severity - Severe, 7-9. ,  
- Associated symptoms - c.Vomiting, c. Fever, c. Decrease in appetite, Nausea,  Anorexia,  Diarrhoea,  Constipation,  Abdominal distention / Bloating,  Belching / Burping,  Flatulence,  Color change in stool [describe],  Blood in stool,  Change in frequency of urinating [describe],  Color change in urine [describe],  Hiccups,  Restlessness,  Injury - 
- Exacerbating Factors - Coughing,  resting on right side. 
- Relieving Factors - None/Denied

(Use round bullets)

**Comment by nehagoel2** [comment]
Note the punctuation errors in the original note:
"-" after the Injury (before exacerbating factors) instead of "."
". ," After severity the comma is not needed

**Comment by dbarretto** [comment]
Cannot add new line characters as openmrs rest APIs does not accept it....

**Comment by amalafrozalam** [comment]
@dbarretto can you post a screenshot of how it looks now after the changes?
@nehagoel2 please confirm via the screenshot that it looks good. Note, new line characters cannot be added. Instead, perhaps we can make it have new line characters on the app side. But it will not have the same display on the OpenMRS side.
