### ISSUE TITLE
Associated symptoms - the text of the parent node "Associated symptoms" is not added to language

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#372]
the history note reads:

......c. blah, c. blah, c.blah, s. blah, s. blah.....

instead of

....Associated symptoms -
c. blah, c. blah, c. blah << new line
s. blah, s. blah              << new line

**Comment by dbarretto** [comment]
@nehagoel2 : I understand the format you need but I don't know what is "c."in "c.blah" and "s." in "s.blah". Can you please explain...?

**Comment by nehagoel2** [comment]
They are abbreviations
c. = Associated with
s. = Not associated with
