### ISSUE TITLE
App is crashing  on compliants screen after downloading mindmaps from parse server 

### ISSUE THREAD

**Issue by prithi69** [Intelehealth/Android-Mobile-Client#378]
![screenshot_20171204-170348](https://user-images.githubusercontent.com/28602886/33551372-364489fe-d917-11e7-9747-4355d7912e27.png)
In this screen, the app is crashing.

when i use demo mindmaps its not crashing,

**Comment by dbarretto** [comment]
Th issue was with Parse server, the patient history file name had an error, so wasn't being downloaded. This has been fixed. To apply fix, just update mindmaps, does not require reinstall of app.
