### ISSUE TITLE
Calculate age as -- yrs -- months

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#380]
In patient registration screen age is measured as years. We need years and months, this is especially for patients who are small children.
If the health worker puts in the DOB, the age should be calculated as -- yrs -- months.
Eg: DOB: 1 Dec 2016 - 0 years 11 months
If the health worker puts in the years and months, the DOB should be calculated.

**Comment by prithi69** [comment]
Give the Apk to test @AniketIntelhealth

**Comment by AniketIntelhealth** [comment]
/*=====================Calculating age in Months=====================
===============================================================*/

mDOBPicker = new DatePickerDialog(this, android.R.style.Theme_Holo_Light_Dialog_NoActionBar, new DatePickerDialog.OnDateSetListener() {
            @Override
            public void onDateSet(DatePicker view, int year, int monthOfYear, int dayOfMonth) {
                //Set the DOB calendar to the date selected by the user
                dob.set(year, monthOfYear, dayOfMonth);

                //Formatted so that it can be read the way the user sets
                SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
                dob.set(year, monthOfYear, dayOfMonth);
                String dobString = simpleDateFormat.format(dob.getTime());


                //Age should be calculated based on the date
                int age = today.get(Calendar.YEAR) - dob.get(Calendar.YEAR);
                int months = today.get(Calendar.MONTH) - dob.get(Calendar.MONTH);
                if (today.get(Calendar.DAY_OF_YEAR) < dob.get(Calendar.DAY_OF_YEAR)) {
                    age--;
                }
                mAge.setText(String.valueOf(age));
                mAgeInMonths.setText((String.valueOf(months)));
                mDOB.setText(dobString);

            }
        }, today.get(Calendar.YEAR), today.get(Calendar.MONTH), today.get(Calendar.DAY_OF_MONTH));
            mDOBPicker.getDatePicker().setMaxDate(today.getTimeInMillis());


        //DOB Picker is shown when clicked
        mDOB.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mDOBPicker.show();
            }
        });

        mAge.addTextChangedListener(textWatcher);
        mAgeInMonths.addTextChangedListener(textWatcher);

**Comment by amalafrozalam** [comment]
Need to completely redo this. This feature does not work at all.

**Comment by amalafrozalam** [comment]
This will be split into 2 fields, years and months. The age textfield will need to be split.

**Comment by amalafrozalam** [comment]
@nehagoel2 i dont understand something. if the health worker is given a number of months, why can't they just use the date of birth picker to calculate the the right birth month?
