### ISSUE TITLE
App crashes on entering negative age

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#385]
App auto calculate calculates negative age if DOB is set to greater than current date. The error dialog pops up, but the age is autocalculated as negative. The app crashes if the health worker does not correct the age.

See crash report on Acra: https://intelehealth.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/intelehealth/bug/ef10172997be52c4fd6a9f301853468d

**Comment by prithi69** [comment]
Give the Apk to Test @AniketIntelhealth

**Comment by nehagoel2** [comment]
This is done,
