### ISSUE TITLE
On erasing & rewriting text written in the history note or physical exam note the previous text still appears

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/Android-Mobile-Client#394]
see eg: this is the first, this is the second for Babu Bholenath on test server (visit on Dec 10).

**Comment by amalafrozalam** [comment]
This is a change to the way the node object stores inputs. There should be a new field for the Node object that stores the input, and when the language is generated, the object looks to see if that field is empty or not.

**Comment by nehav39** [comment]
Duplicated issue - further work done n #762
