### ISSUE TITLE
Even after locations are fetched "Unable to fetch locations" toast notification shows up on Setup screen

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#401]

**Comment by nehagoel2** [comment]
@amalafrozalam - can someone please work on this - its a bit annoying and doesn't look good to new clients!

**Comment by nehagoel2** [comment]
@dbarretto - very minor fix. The toast notification shows up after entering barely 3-4 characters and then persists for a long time obscuring the keyboard.
We definitely need to reduce the time for which the notification is displayed. But we also need to give the user sufficient time to enter the url before telling that that we're "unable to fetch locations"

**Comment by dbarretto** [comment]
@nehagoel2 This issue has been fixed. Please pull branch issue-401. Please review and close this issue.
