### ISSUE TITLE
Aftet restoring the back up in the app, while printing the patient prescription, the app crashes.. 

### ISSUE THREAD

**Issue by prithi69** [Intelehealth/Android-Mobile-Client#402]

**Comment by dbarretto** [comment]
@prithi69 : I need more info on this one... Please send me a screen shot of the complaint note. Also does the complaints have an arrow bullet (►)?

**Comment by prithi69** [comment]
This issue got solved after installing the latest apk (intelehealth_1312207), but there is a another issue, after restoring the back when i update the mindmap, the app crashes.. tested in moto e4 and my phone redmi note 3.

**Comment by nehagoel2** [comment]
Is this issue completed? @prithi69 can we close it?

**Comment by prithi69** [comment]
Yes, its fixed we can close it.
