### ISSUE TITLE
Pressing the upload button multiple times , data are getting posted multiple times in the database

### ISSUE THREAD

**Issue by prithi69** [Intelehealth/Android-Mobile-Client#409]

**Comment by nehagoel2** [comment]
Examples? More information?

**Comment by prithi69** [comment]
Example: If you press the upload button, data get posted in the database, with the obs_id, and again if you press the upload button again, same data will get posted again with different obs_id, 
So it should not happen, if we press the upload button again, same data will not get get posted with different obs_id, , it should remain same until any changes being done in the app.

**Comment by nehagoel2** [comment]
Fix: Deactivate the upload to doctor button once it has been pressed. Only reactivate it if the health worker changes something on the Visit Summary screen (like editing some part of the note).

**Comment by nehagoel2** [comment]
For the fix suggested above need to look into the upload service for what happens when the user initiated upload is added to the queue when there is no data connection
