### ISSUE TITLE
Display name should be removed from Setting screen

### ISSUE THREAD

**Issue by AniketIntelhealth** [Intelehealth/Android-Mobile-Client#412]

**Comment by nehagoel2** [comment]
Are we even using this Display Name feature anymore?

**Comment by AniketIntelhealth** [comment]
no @nehagoel2  so it is removed for now from the app

**Comment by amalafrozalam** [comment]
In the settings screen, the health worker's name can be removed. That does not need to be set.

**Comment by amalafrozalam** [comment]
Removed this, and also removed the general header in the settings activity.
