### ISSUE TITLE
HTML tags with the complaints and physicals

### ISSUE THREAD

**Issue by prithi69** [Intelehealth/Android-Mobile-Client#414]
![image](https://user-images.githubusercontent.com/28602886/34939001-47775192-fa10-11e7-97bc-bdfd282a2101.png)

**Comment by nehagoel2** [comment]
Needed for Haiti deployment.

**Comment by nehagoel2** [comment]
HTML tags with the complaints and physicals are getting posted in the database, after posting complaints and physical exam from the app.
When you hit "Manual entry" to edit the patient history note on the app's Visit summary screen, these tags are there too.

**Comment by amalafrozalam** [comment]
Lines 641 - 642
That's where the textView value is set. The complaint is gotten from the database, formatted, then set to the textView. @AniketIntelhealth you need to change the ClickListeners for each of the edit screens, change their textView values to the database value instead of the HTML value. So for example, in line 701, it should just be famHistTest.setText(famHistory.getValue())

Also, it should be famHistText. Please change that.

**Comment by AniketIntelhealth** [comment]
@amalafrozalam  @nehagoel2  @prithi69 so When user  hits "Manual entry" to edit the patient history note on the app's Visit summary screen, these tags are not displayed .but still they are posted in database .

**Comment by nehagoel2** [comment]
@AniketIntelhealth  this is the last time I am closing the issue. You consistently forget to do this!!!!!

**Comment by AniketIntelhealth** [comment]
/*===========When you hit "Manual entry" to edit the patient history note on the app's Visit summary 
                        screen, <br> tags are showed up=====================*/


1.In the below code "famHistText.setText(Html.fromHtml(famHistory.getValue()));"  this line prevents <br> 
   or <b> tags getting displayed on the screen.
2. same goes with other attributes like physicalHistory,Vitals,patientHistory and so on!!

        editFamHist.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                final AlertDialog.Builder famHistDialog = new AlertDialog.Builder(VisitSummaryActivity.this);
                famHistDialog.setTitle(getString(R.string.visit_summary_family_history));
                final LayoutInflater inflater = getLayoutInflater();
                View convertView = inflater.inflate(R.layout.dialog_edit_entry, null);
                famHistDialog.setView(convertView);

                final TextView famHistText = (TextView) convertView.findViewById(R.id.textView_entry);
                if (famHistory.getValue() != null)
                    famHistText.setText(Html.fromHtml(famHistory.getValue()));
                famHistText.setEnabled(false);

                famHistDialog.setPositiveButton(getString(R.string.generic_manual_entry), new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialogInterface, int i) {
                        final AlertDialog.Builder textInput = new AlertDialog.Builder(VisitSummaryActivity.this);
                        textInput.setTitle(R.string.question_text_input);
                        final EditText dialogEditText = new EditText(VisitSummaryActivity.this);
                        if (famHistory.getValue() != null)
                            dialogEditText.setText(Html.fromHtml(famHistory.getValue()));
                        else
                            dialogEditText.setText("");
                        textInput.setView(dialogEditText);
                        textInput.setPositiveButton(R.string.generic_ok, new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialog, int which) {
                                famHistory.setValue(dialogEditText.getText().toString());
                                if (famHistory.getValue() != null) {
                                    famHistText.setText(Html.fromHtml(famHistory.getValue()));
                                    famHistView.setText(Html.fromHtml(famHistory.getValue()));
                                }
                                updateDatabase(famHistory.getValue(), ConceptId.RHK_FAMILY_HISTORY_BLURB);
                                dialog.dismiss();
                            }
                        });
                        textInput.setNegativeButton(R.string.generic_cancel, new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialog, int which) {
                                dialog.dismiss();
                            }
                        });
                        textInput.show();
                        dialogInterface.dismiss();
                    }
                });
