### ISSUE TITLE
Create card for 'Follow-up visit' on the Visit Summary, also a pop up after clicking End Visit

### ISSUE THREAD

**Issue by vibhabhirud** [Intelehealth/Android-Mobile-Client#433]
To remind Sanyogikas to ask the patient for a follow-up visit, create a pop-up with the following description  after the Sanyogika's click 'End visit'.
'Ask the patient to come for a follow-up visit:
- as adviced by the doctor or when the medication 
- with test reports
- when the medication dose is complete'

**Comment by nehagoel2** [comment]
Vibha we need to discuss this. The doctor needs to set a follow up date and include it in the Doctors' comments. Sanyojikas can't be expected to do this.
This is a training point for doctors and Sanyojikas.
Also this is an implementation specific feature. so we will need to discuss about the best way to implement this.

The underlying user need is: Health workers need a reminder to communicate the date of follow up visit to the patient.

**Comment by nehagoel2** [comment]
Also needs to be in the prescription print out given to the patient and the SMS sent to the patient

**Comment by nehagoel2** [comment]
Related to #73 on the OpenMRS side

**Comment by nehagoel2** [comment]
What's the UUID for the follow up date obs created?

**Comment by hardikk08** [comment]
Follow Up Visit uuid - e8caffd6-5d22-41c4-8d6a-bc31a44d0c86

**Comment by hardikk08** [comment]
@amalafrozalam Take the following steps -
1. You will need the {visitId}
2. Query /visit/{visitId}
3. The response will contain obs which contains display values of all obs, you have to fetch the follow up value then. See the attach. below to understand better.

![image](https://user-images.githubusercontent.com/29514954/37901047-b79d38ea-310d-11e8-8fcc-f1fbc66a184c.png)

**Comment by amalafrozalam** [comment]
@hardikk08 concept ID for follow up visit?

**Comment by amalafrozalam** [comment]
@nehagoel2 and @vibhabhirud 
Just want to clarify, are we definitely doing the pop up? Or just leave it as a card on the visit summary screen?

**Comment by amalafrozalam** [comment]
Follow up date concept id: 163345

**Comment by nehagoel2** [comment]
Don't forget to add the follow up date to the printed prescription and the SMS prescription

**Comment by amalafrozalam** [comment]
Reminder to do the alert dialog, when they end the visit.

1. Click end visit
2. Follow up dialog is shown
3. They click okay to acknowledge
4. They go to the patient exit survey

**Comment by prithi69** [comment]
Bug - 1:
![screenshot_20180402-132508](https://user-images.githubusercontent.com/28602886/38189776-2cf797ea-367f-11e8-9184-17532cb68b66.png)
![screenshot_20180402-132526](https://user-images.githubusercontent.com/28602886/38189787-3302d500-367f-11e8-9ca8-4b7e1feced18.png)

 Rename the card of follow up visit, its showing Additional Comments.
Bug - 2: On the prescription, follow up visit is coming on the Doctors note, and doctor's note is missing.
