### ISSUE TITLE
Add activity to collect patient exit survey at the end of end visit

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#436]
After hitting end visit, the health worker should be presented with the screen for patient satisfaction survey.
@Vibha can provide more details about the survey.

**Comment by nehagoel2** [comment]
Needs to be pictographical, example: 
![image](https://user-images.githubusercontent.com/14187848/36013006-c3bf91c4-0d2f-11e8-8e29-c6e37e978183.png)

**Comment by prithi69** [comment]
@nehagoel2 , there is no obs type table in the database, we can create encounter_type called patient_satisfation.

**Comment by nehagoel2** [comment]
Ok, but you will need to create a concept ID for storing the entry into obs table.

Call the encounter "Patient Exit Survey"
And the obs concept ID "patient satisfaction" ---> for the smiley faced
And another obs concept ID called "comments" ---> for general feedback as a text input.

@amal based on the smiley face chosen the value 1-5 should be entered into the database. 1 - very good, 5 - very bad, so we are collecting this info on a likert scale.

**Comment by prithi69** [comment]
Uuid for encounter type Patient Exit Survery : 629a9d0b-48eb-405e-953d-a5964c88dc30
Obs_concept_id nam " Patient satisfaction " --- > 163343
another concept_ID "called "Comments" ---> 163344

**Comment by amalafrozalam** [comment]
This activity should only display "How was your experience?"
And then it should display the smileys :) and :(

And then a space for comments

**Comment by amalafrozalam** [comment]
Add an option to skip the survey. Also keep a poker face, so neutral.

5 gradations of faces

**Comment by amalafrozalam** [comment]
![screen shot 2018-03-24 at 11 54 22 pm](https://user-images.githubusercontent.com/3815106/37871575-bcaa9bfc-2fbe-11e8-933c-0076799060c8.png)
This is what the screen looks like right now. @nehagoel2

**Comment by amalafrozalam** [comment]
This issue is almost complete. It just needs the values of the UUIDs for "Patient Satisfaction" and "Comments"

@prithi69 will provide those values here.

**Comment by prithi69** [comment]
Patient Satisfaction UUID : 78284507-fb71-4354-9b34-046ab205e18f
Comments UUID : 36d207d6-bee7-4b3e-9196-7d053c6eddce

**Comment by nehagoel2** [comment]
Buttons look UGLY

**Comment by nehagoel2** [comment]
This screen looks UGLY

**Comment by nehagoel2** [comment]
Black is hard to read against the grey. Buttons need to be changed everywhere.
Function over form for now.

**Comment by prithi69** [comment]
Patient encounter_type is not being posted on the database.

**Comment by amalafrozalam** [comment]
@prithi69 do you mean the encounter type for the patient exit survey? It follows the same exact code as another other encounter, so I'm too sure of the reason. 

Which server are you testing on? Have the changes been implemented there?

**Comment by amalafrozalam** [comment]
So I have absolutely no idea why this isn't posting correctly. The JSON stream is correct, and so no idea what's happening here. @hardikk08 any ideas?

**Comment by amalafrozalam** [comment]
Just fixed it. I added an extra comma.
