### ISSUE TITLE
Encounter provider not posted from Android app

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/Android-Mobile-Client#447]
Part 1: POST. Posts the health workers provider ID as the provider for the Vitals and ADULTINITIAL encounter.

Part 2: GET. The data received from OpenMRS contains the doctor's provider ID for the encounter_provider for the Visit Note encounter. This provider data of the doctor's name needs to be displayed on the Visit Summary screen and in the printed prescription and SMS.

OpenMRS side work is done.

**Comment by amalafrozalam** [comment]
Because I constantly get confused by this, the health worker's ID doesn't get posted. So this needs to be somehow gotten from the setup screen and/or the login screen. Not really sure which endpoint to use, so this is currently the barrier for this issue.

**Comment by amalafrozalam** [comment]
I think maybe using the "/session" endpoint might work, but I need to test.

**Comment by hardikk08** [comment]
So @amalafrozalam this is what I believe you will need to do,
1. Fetch encounter of type visit note, you will get a {uuid}
2. Then query /encounter/{uuid}
3. From the response you will have to fetch the encounter providers and use the display object. 

Check the attachment to get a better idea.
![screenshot 16](https://user-images.githubusercontent.com/29514954/37890955-1c20a7f2-30f0-11e8-9ae7-9be3b9967875.png)

**Comment by amalafrozalam** [comment]
So the client service needs to be updated to post with the CHW provider id.

**Comment by amalafrozalam** [comment]
When the Rx is downloaded, you need to grab that encounter provider UUID, cause for the doctor's stuff, the doc is the encounterProvider. From there, run a query on the visit, get the doc's name, and display that.

**Comment by amalafrozalam** [comment]
1. CHW logs in --> get the CHW UUID at this point
2. When posting a patient record, post with the CHW UUID.
3. When downloading, look for the encounterProvider for the downloaded record.
4. Use that encounterProvider to query locally first for the doctor's name, and if not found, query the server for the name. Make sure to save into the DB if isn't there.

**Comment by amalafrozalam** [comment]
So the UUID of the doctor is being stored, so is the name. The challenge now lies in the fact that the obs returned from the doctor need to saved with the doctor's UUID. When VisitSummary queries the DB to get this data, it will also need to query the user_providers table with the doctor's UUID to find the doctor's name to ultimately display it.

**Comment by nehagoel2** [comment]
Reopened - as this feature was rolled back in #465 to fix the app crashing and database crashing issues.

**Comment by nehav39** [comment]
Branch: reverted-back
