### ISSUE TITLE
Cloud back up of Android db

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#450]
So that we can restore from a cloud back up at set up instead of a local back up

1. Device takes local back up on the phone in the night
2. Device uploads the local db to parse over a service (service tries until it receives a success notification)
3. At setup, based on the device location, the app downloads the most recent back up from the cloud.

Devices are breaking more frequently than we thought they would.

**Comment by dbarretto** [comment]
Why should it be based on the location and not on the uuid of the health worker? I am worried that there can be multiple health workers working at the same location (locations can be very coarse), which can cause either a wrong db file to be delivered or even files to override each other.

**Comment by amalafrozalam** [comment]
I agree, I didn't realize the issue said location. I think it would be better to ID the files based on the ID of the device or some sort of assigned name. So it can be something like Location X device 1, device 2, etc. I think the health worker UUID might not work in case the tablet is shared. 

Regardless, I am in complete agreement that there needs to be a way to identify tablets to a specific location.

**Comment by dbarretto** [comment]
@amalafrozalam This can cause another problem, if the device breaks, then the new device will have a separate identifier, so the new device won't be able to get the backup.

**Comment by amalafrozalam** [comment]
Right, that's why some sort of assigned name might be better. So when tablets are provisioned, they are assigned a group name.

Example:
Location is NYC
There are 3 tablets, each designated Queens, Brooklyn, Manhattan. 
If the Brooklyn tablet breaks, it's fine. When a new tablet is set up, it is just synced with the previous Brooklyn tablet's data. If there are multiple Brooklyn tablets, then they are further sub-identified with a number (Brooklyn-1, Brooklyn-2, etc).

**Comment by nehagoel2** [comment]
Folks - just wanted to correct some things here. On the OpenMRS side there are locations and there are providers. Currently we have only one provider at each location. When we have multiple providers at each location then we would need to make sure all apps in one location are in sync - all patients at a location should be visible to all providers at that location.

So in the later issues of this milestone, we need to implement a true patient sync. This issue #450 is only an interim fix for the short term, so there is no need to invest so much time in it. 

The need is very simple - we just need a back up of each app, and at the moment there is only one app and one location corresponding to each provider. So seriously, don't invest so much time in figuring this out. Just pick the easiest path, in some time, when we implement true patient sync, this feature will no longer be needed.

**Comment by dbarretto** [comment]
@nehagoel2 Okay, I am a bit confused now, can you give me an example of the location you are referring to? Are you referring to locations that we fetch during setup eg: Remote, Telemedicine Clinic 1, etc?

**Comment by amalafrozalam** [comment]
Yeah, she means those locations. Remote, Telemedicine Clinic 1, etc.

**Comment by nehagoel2** [comment]
@dbarretto - status update on this issue please?

**Comment by nehagoel2** [comment]
**Functionality to be tested:** 
Manual upload - 
Restore - if there is data in the database it will not restore. if there is a local back up restores from there. If no local back up, download from parse.
Forceful restore - restores from cloud always. It clears out all the data and restores the db from scratch. Are you sure?
Database is tied to a combination of a user and a location.

Test the automatic back up to cloud. Install the app, create some patients (don't manually upload to the cloud) and wait to see if a backup is created automatically on the cloud.

Translations required of the strings.

**Comment by nehagoel2** [comment]
Workflow of restoring from local back up for whatsapp (after entering the phone number and entering the OTP received).
![screenshot_20180609-191658](https://user-images.githubusercontent.com/14187848/41192400-ba03aa0e-6c1a-11e8-8591-eeabf2b68c3b.png)
![Uploading Screenshot_20180609-191706.png…]()
![Uploading Screenshot_20180609-191723.png…]()
![Uploading Screenshot_20180609-191729.png…]()




See attached

**Comment by nehagoel2** [comment]
When I restored whatsapp from local backup any messages I sent in the last 20 hours or so weren't there.

**Comment by dbarretto** [comment]
It is because your last backup was done 20 hours ago. So all data after that was lost.

**Comment by dbarretto** [comment]
Unfortunately Android does not provide an app uninstall notification for devices.

**Comment by nehagoel2** [comment]
@dbarretto - just confirming, when the user logs out of the phone the local db and the cloud db are backed up? Or is it just the local db that is backed up?

**Comment by nehagoel2** [comment]
One consequence of this sort of technique for data backup is that we have to make absolutely sure that one person is only logged into one device at one time.
And that means changing some testing protocols for us (eg: for a recent deployment, a user was unable to login to their account from the app, so we tested it by logging in from our test device.)

**Comment by nehagoel2** [comment]
@dbarretto - Testing report:

Queries: On hitting "backup" from the settings menu - does the app take a local backup or both a local backup + upload to cloud? When you logout of the app - does the app take a local backup or both a local backup + upload to cloud?

Bug fix:
Every time the app is opened, it asks if you'd like to restore from a local backup - this only needs to happen at the time of setup, not every time the app is opened

**Comment by dbarretto** [comment]
@nehagoel2 It does bot as long as there is internet else it only does local and adds a task to the queue which is checked every 1/2 hour.
Let me check...  I'll fix it by tonight

**Comment by nehagoel2** [comment]
@dbarretto - what about the other queries? On hitting "backup" from the settings menu - does the app take a local backup or both a local backup + upload to cloud? When you logout of the app - does the app take a local backup or both a local backup + upload to cloud?

**Comment by AmbujPandey** [comment]
Until now the " backup " from the setting menu is store as local backup. The is backup is not able to upload to cloud. Even backup is not happening on night (8 PM / 10 PM).
When you logout of the app - it takes the local backup, not upload to cloud.

If  i newly install the app and intelehealth.db file is present in internal storage, it access the .db file which contain the updated patient also.

**Comment by nehagoel2** [comment]
Automatic backup: At 7:30 pm each night a local back up is taken and its pushed to the cloud. If there is no internet at that point of time, it will make a local backup and adds the cloud push to the delayed jobs queue and it will get uploaded to the cloud when the internet comes back on.

Backup: On clicking backup, a local backup is created (toast notification) and it is pushed to the cloud (push notification will be received). If there is no internet at that point of time, it will make a local backup and adds the cloud push to the delayed jobs queue and it will get uploaded to the cloud when the internet comes back on.

Same thing happens on "Logout".

Restore: If data exists in the app db, do nothing. If no data in app db, and there is a local backup, it restores the local backup. If no data in app db, and there is no local backup, it restores from the cloud. If no data in the app db, no local backup and no cloud backup - do nothing.

Forceful Restore: Restore the data from the cloud.

**Gaps:**
If app is killed then the local backup won't be taken at 8:30 pm.

**Comment by nehagoel2** [comment]
Automatic backup - check today if its working
Backup - working properly. Can make some improvements in a new version with regards taking a backup before uninstalling the app
Restore - data restore is working properly, image restore has a problem (see issue #472 for details about this)

=====
Future work: 
Take a backup before uninstall

Edge case: A patient is created when there is no internet connection. They don't have an identifier since they have not been uploaded, when the back up is created while the phone is still offline, there is no identifier for the patient in the local database. Then when the internet connection is turned on, the new patient gets created on OpenMRS, their identifier is received on the phone, and in the local app db. But its not on the backup, since the backup was created at a time when there is no internet connection.
