### ISSUE TITLE
Multiple visits are being posted in the OpenMRS database by the app

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#453]
This only happens occasionally.

One hypothesis is due to a jittery network.

**Comment by nehagoel2** [comment]
we need to figure out why this is happening?

**Comment by nehagoel2** [comment]
This could be a device specific issue as well

**Comment by nehagoel2** [comment]
This has been observed on the Haiti side, on AFI very very early on - in January, and during demo.

**Comment by nehagoel2** [comment]
What's the optimum time out time?

**Comment by dbarretto** [comment]
@nehagoel2 : I believe that the current timeout is 30 sec (Please confirm this @hardikk08 and @amalafrozalam). I would suggest increasing it to 1 minute and trying it out for a week to see if the issue persists.

**Comment by amalafrozalam** [comment]
HttpURLConnection con = (HttpURLConnection) url.openConnection();
con.setConnectTimeout(5000); //set timeout to 5 seconds

This needs to be added to HTTP connections. The time should be set accordingly (5 seconds is long).

**Comment by amalafrozalam** [comment]
It's not set to anything right now, it's just set to the default. I was just posting the code here for reference purposes later one. 

I agree, this should be tested and determined for the conditions we want to work in. The current timeout is the default for network connections (I forget the exact number), but clearly that only works for some cases, not all.

**Comment by nehagoel2** [comment]
This issue is still occurring - we have to increase the time out and send a new apk release file.

**Comment by prajwalhacker** [comment]
It happened in case of slow internet connection. The connection timeout time was set to 15 sec. nd the read timeout was set to 30sec.....due to which the problem was there.....as it was again after 15secs sending a new request ......so I updated the connection timeout - 1 min and the read timeout- 2 min. Then I added a patient in low network connection and checked the open mrs ......nd there only one record is been created of mine ......even when it was created in slow network connection!

**Comment by prajwalhacker** [comment]
So I guess, the bug has been solved out !

**Comment by nehagoel2** [comment]
Occurred in AFI server on 16th August (see ticket No. 132 on Zoho for more details)

**Comment by AmbujPandey** [comment]
This again crash happen may be because of 3 reasons
- Network Jerking
- server didn't response
- Low Bandwidth
There is no similarities(location,timing) between 2 patients.

**Comment by nehagoel2** [comment]
After careful observation of this issue for many months:
It appears that the server response code is not received within the connection time out time and read time out time that was set. This is especially observed when server is in a different country, increasing latency issues.

Suggested solution - increase the read time out and connection time out even further. Do some additional testing.

**Comment by nehagoel2** [comment]
Kundan's solution:
**Current state:-** 
POST visit. WAIT 2 mins for server response. If no server response, try again
POST encounter. WAIT 2 mins for server response. If no server response, try again

**Fix:-** 
POST visit. WAIT 2 mins for server response. If no server response, check if visit exists. If visit does not exist try again else POST encounter.
If visit uuid exists in database, do nothing. Else add to local db
POST encounter. WAIT 2 mins for server response. If no server response, check if encounter exists. If encounter does not exist, try again else POST encounter.

**Comment by kranthi-mahiti** [comment]
If no response comes from the server, it is not known whether the visit has been created in the server or not. If the visit uuid does not come back in response, Everytime a post request is sent from the mobile openMRS will treat this as a new visit. If we do not get the visit uuid from openmrs , how can we check visit uuid with the database?. This issue needs to be discussed

**Comment by kundanmail55** [comment]
To check the patient has visit or not. 
http://demo.intelehealth.io/openmrs/ws/rest/v1/visit?patient='patientuuid'

**Comment by kranthi-mahiti** [comment]
In recent days no duplication of visits is entered. I check in the demo.intelehealth.io

**Comment by CharanMaddireddy** [comment]
Today, Myself and Sajan cross verified the flow of submitting the Visit (Its became duplicate entry)

from the current application flow once click on Upload to doctor a new visit is being created, but still button will be in visible mode where health worker can submit as many times. So the API for visit creation is getting called as many times in the same.
**Solution 1:** To avoid duplication, Once one visit is done and there is an UUID in android app. then we should stop calling the API.
we will be applying this logic.
