### ISSUE TITLE
All mind maps (except Demo mind maps) disappeared from the Complaint screen

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/Android-Mobile-Client#461]
On 4th May health workers at Fingamunda and Magarmohan setup their phones, saw patients for two days, on the 6th they noticed their phones no longer had all the mind maps and only the demo mind maps were remaining.
They did not update mind maps or clear phone data

**Comment by nehagoel2** [comment]
This happened again on 14th May for the Fingamunda device.

**Comment by nehagoel2** [comment]
During set up, the user selected Download mind maps.
The app also is using the backed up database.

**Comment by nehagoel2** [comment]
@dbarretto @amalafrozalam - any ideas on why this may be  happening and how we can identify the cause?
