### ISSUE TITLE
Different physExam, patHist and famHist files for different deployments 

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#462]
For RHPT we have different patHist, famHist and physExam files, the app requires the files to be named exactly like this. When we store these new mm files on the mind map server, we will not be able to assign them to a license key.
Potential solution 1 - assigning mm files to license keys by their unique ID, not name
Potential solution 2 - app naming system for physExam, patHist and famHist

**Comment by nehagoel2** [comment]
@dbarretto - what solution are you going to use? Any of the ones I suggested or something else?

**Comment by nehagoel2** [comment]
May 19th email from Dexter: 

Issue #462 has been fixed. I have made a commit on Github on the branch Issue-462. I have tested it on my side and it seems to work.

The fix is on the Android side so the clients need to be updated before receiving this feature. Changes on the server do not affect the existing clients and they can continue to function with the old feature as long as the old files are available on parse.

When adding Physical Exams, Past Medical History and Family History Files, you can add an extension to the name, which can be used by the server to identify the correct file.

For example, you can have file names like. It is not necessary, but for simplicity sake, the original file name is in CamelCase and the Extention is in ALL CAPS. 

physExamRHPT.json
patHistAFI.json
famHistORI.json

Just don't change the original part of the name (like physExam for Physical Exam).

**Comment by dbarretto** [comment]
@Neha Goel<mailto:neha@intelehealth.io> I tested it and it is working as required. Though have @hardik@intelehealth.io<mailto:hardik@intelehealth.io> Test it before release. It is always good to have a second review. Also, I test on Emulators and my Asus device (Which runs on Android 6.0), so it will be good if he can test on the actual device that we are deploying to.


Also please confirm what hardware would you want to release the Parse Server on.

Note: You will still face some connection refused issues from Parse Server, especially if the Parse Dashboard is in use.


Regards,
Dexter Barretto
________________________________

**Comment by hardikk08** [comment]
I have tested this using the key 'rhptdemo' which had phyExamRHPT.json in it and it worked fine. @nehagoel2

**Comment by nehagoel2** [comment]
@dexterbarretto - please close your issues when they're done!
