### ISSUE TITLE
Formatting of BP readings in physical examinations

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/Android-Mobile-Client#463]
See screenshot. The BP readings from physical exams mind maps language aren't formatted.
Potential solution is to change the logic of how formatting is added when sibling nodes are selected and/or when multiple nested nodes are parsed through

**Comment by nehagoel2** [comment]
![screenshot_20180504-010210](https://user-images.githubusercontent.com/14187848/40094464-2b1e96e8-5895-11e8-857d-173027483bd5.png)

**Comment by nehagoel2** [comment]
See Android Slack channel for the corresponding mind map

**Comment by nehagoel2** [comment]
See commit 7191d35 on the mm repo - some changes have been made to the language attributes of the physExam mind map for better formatting and improved readability. It is not an ideal solution, but a decent interim solution. Please use the updated physExam mm for RHPT and check to see if the BP readings are simpler to read.
