### ISSUE TITLE
App should have a button to view in the local language without having to change system language

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#464]
In order to allow third party apps to modify phone language some steps need to be taken to enable permissions for third party apps to modify the phone language using ADB commands.
https://docs.google.com/document/d/1eiOPBXNmaqeJ2xeEKE57amha8babnDP1Po95_R72_sk/edit#
The document above mentions the steps to do this.

However this is not a user friendly option.

USER NEED: We need a more user friendly way to set the app language to Odiya and we need a more user friendly way to set the system language

Having the app set up in a way that the app itself can change its own language - this would require adding a button to the settings screen or to the home page.

Should be pretty easy to do

**Comment by nehagoel2** [comment]
Amal estimates 10 hours of dev work for solution 3.
1. Add the button on the home screen and set up the hook 
2. Listener when the language is changed - changing the app language and restarting the app to reflect that change

**Comment by amalafrozalam** [comment]
@nehagoel2 we decided it was the home screen?

**Comment by nehagoel2** [comment]
@amalafrozalam - yes on the home screen.
