### ISSUE TITLE
App crashes when server returns no response

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/Android-Mobile-Client#468]
Message from @amalafrozalam: 
issue with the server response actually
i didnt actually know this was possible, but it looks like what happened was that it tried to connect to the server and it returned absolutely no response
usually you get at least like a 400 of some sort, but this was completely blank and null
just checked, this is a simple fix. just need to comment out line 1351 in ClientService, and just check if something like that exists anywhere else
i dont believe so, but if anyone wants to double check that'd be most welcome

**Comment by nehagoel2** [comment]
See Firebase crashes June 5, June 7 
ClientService.java line 1351
io.intelehealth.client.services.ClientService.endVisit
