### ISSUE TITLE
Image restore

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/Android-Mobile-Client#472]
Currently when restoring, we can only restore data from backup not images. Images are not being backed up.

**Comment by nehagoel2** [comment]
Same as #398 - 398 has been closed.

**Comment by dbarretto** [comment]
@nehagoel2 I have started researching this issue. I will be working on this issue next weekend, probably should be able to close it too.

**Comment by dbarretto** [comment]
List of strings that were added in feature 450 & 472 and need translation

[strings to translate.xlsx](https://github.com/Intelehealth/Android-Mobile-Client/files/2109034/strings.to.translate.xlsx)

**Comment by dbarretto** [comment]
@nehagoel2 This feature is completed. Please pull branch issue-472 and test it on the deployment devices. Please provide me with feedback, and if there is nothing to chnge the please close this issue for me.

**Comment by nehagoel2** [comment]
@dbarretto - what initiates this restore feature? When you hit "Restore" option or "Forceful restore"?

**Comment by nehagoel2** [comment]
Testing is currently underway.

**Comment by AmbujPandey** [comment]
After  new installation of application when we restore the  image data is downloaded successfully  BUT in patient profile the  image is showing the default image .      Slack  " Tech-android " for more details.

**Comment by nehagoel2** [comment]
On hitting the "Restore" or "Forceful Restore" buttons - Not all images are downloading. The Push notification says (8/10 images downloaded, 3/7 downloaded)
