### ISSUE TITLE
Lock location to a particular device

### ISSUE THREAD

**Issue by vibhabhirud** [Intelehealth/Android-Mobile-Client#477]
To prevent deemed local db from being over-written, one location had to used only by one device. Link every device to a particular location so that no other device should be able to use that location.

**Comment by nehagoel2** [comment]
Testing report - this is not working. Was able to login from three different devices at the same location.
Only difference was that if I logged into two devices with the same user at the same time, a toast notification of "Already logged in" popped up on the screen. But it did not prevent me from logging in.

**Comment by nehagoel2** [comment]
@prajwalhacker tested this. Tested on two different phones - 
If you login to Location 1 with User 1 on Phone 1 and Location 2 with User 2 on Phone 2 - allowed
If you login to Location 1 with User 1 on Phone 1 and Location 1 with User 2 on Phone 2 - not allowed ("Another user logged in")

Changes to be made:
If you login to Location 1 with User 1 on Phone 1 and Location 1 with User 1 on Phone 2 - this is currently allowed - THIS SHOULD NOT BE ALLOWED

**Comment by nehagoel2** [comment]
If you login to Location 1 with User 1 on Phone 1 then you log out, and then login to Location 1 with User 2 on Phone 2 - is this allowed?
If you login to Location 1 with User 1 on Phone 1, then you log out, and then login to Location 1 with User 1 on Phone 2

**Comment by prajwalhacker** [comment]
User Case (v) : is working !!!

**Comment by prajwalhacker** [comment]
Use Case (iv): is also working !

**Comment by prajwalhacker** [comment]
User case (i) : working !
User case(ii) : not working !
User case (iii) : is working with toast message "Already logged in !"

**Comment by prajwalhacker** [comment]
As per the observation , 
case 2 nd case 4 are basically same.....just the difference is -

In case 2 User1 is still logged in due to which we r not able to login with error mes- "Another person logged in".....

whereas ...

In case4- User1 has logged out nd thus User2 is able to login in !

**Comment by prajwalhacker** [comment]
Changes to be made:
Use case (iii): If you login to Location 1 with User 1 on Phone 1 and Location 1 with User 1 on Phone 2 - this is currently allowed - THIS SHOULD NOT BE ALLOWED

-- solved this bug !
