### ISSUE TITLE
Build APK does not have the latest changes from version 1.2.3 on the Playstore

### ISSUE THREAD

**Issue by AmbujPandey** [Intelehealth/Android-Mobile-Client#483]
1.  Demo Mind-map are not showing on (450,472,477) build apk. I started visit, after vital there should be the complaints/symptoms to get the patient problem but there is not option present. 
2.  In RHPT mind-map, the view (it show all symptoms) are totally different from real availability . 
![screenshot_20180704-172157](https://user-images.githubusercontent.com/24957597/42276553-ce248198-7fb1-11e8-9e35-87bca7d095b0.png)
which should be like this.
![screenshot_20180704-172253](https://user-images.githubusercontent.com/24957597/42276561-d425c138-7fb1-11e8-8aaa-7ab4fa3b2326.png)
I think this is happening via some version problem. I faced same RHPT problem 1 month before but when i upgraded the application it showed perfectly.

3. AFI mind-maps are working properly.

**Comment by nehagoel2** [comment]
Demo mm json files shared with @dexterbarretto so that they can be included in future apks

**Comment by nehagoel2** [comment]
For point no. 2, @dbarretto  - it seems that the branch you compiled on it not up to date with the playstore release.
@amalafrozalam - there is a seperate branch for version 1.2.3, how are we doing branch/repo management?

**Comment by AmbujPandey** [comment]
For point no. 1, The mind-map is not showing all the bundles of Demo mind-map.

For point no. 2, It's working fine to the latest version.
