### ISSUE TITLE
Link the visit summary to date of visit instead of 'Active' tab for active visits (below 'Start new visit')

### ISSUE THREAD

**Issue by vibhabhirud** [Intelehealth/Android-Mobile-Client#499]
On Patient information screen, below 'start new visit' button:
When the users has to go to visit summary of an old patient, he/she has to click on green 'Active' tab (if the visit is active) or the date of the visit (if the visit has ended). This confused the users as they try to click the date of visit for active visits

There should be a standard method to go to visit summary of old patients. In this case, link the visit summary to date of visit even in active patients. (This method is followed even on OpenMRS)

**Comment by nehagoel2** [comment]
You can click on the date of the visit or the active tab for an active visit to open up the visit summary screen. Tested this on current app version.
