### ISSUE TITLE
Client Service attempts to start service while app is in background

### ISSUE THREAD

**Issue by AmbujPandey** [Intelehealth/Android-Mobile-Client#500]
App crashing on "JobDispatchService.java line 127 & JobDispatchService.java line 116"
Originator-  Ambuj Pandey
Status- OPEN
User Affected- 1
Checked from- July 19,2018
Bug type- Coding error

Environment:
Mobile Brand-            Xiomi          
Model-                       Mi A1
OS Version-               8.1.0  ,8.0.0
App Version-             1.3.3 , 1.2.3
Started-                     July 23th, 2018 
Number of Crashes:   201

Summary:  Fatal Exception: java.lang.IllegalStateException
Description:
     Not allowed to start service Intent { cmp=io.intelehealth.client/.services.ClientService (has extras) }: app is in background uid UidRecord{f5918fe u0a121 TRNB idle change:uncached procs:1 seq(0,0,0)}
    io.intelehealth.client.services.sync.JobDispatchService.onStartJob (JobDispatchService.java:127)
  Crash is Happening continuously on a single user many  times. It started on July 23th, 2018 for :127 and June 11th, 2018 for:116.  

URL:   [click_here](https://console.firebase.google.com/u/0/project/mobile-crashlytics/crashlytics/app/android:io.intelehealth.client/issues/5b5687986007d59fcd8af88b?time=1531958400000:1533772799000&sessionId=5B69962501C400011B599BE33B8D7779_DNE_0_v2) for :127
[click_here](https://console.firebase.google.com/u/0/project/mobile-crashlytics/crashlytics/app/android:io.intelehealth.client/issues/5ac0e6b836c7b23527426b5b?time=1531958400000:1533859199000&sessionId=5B38421D01640001297C9BE33B8D7779_DNE_0_v2)for:116

**Comment by amalafrozalam** [comment]
This is likely occurring because the user has moved away from the app and is using a different app. The app is now considered to be in the background, but is attempting to upload images and other data that wasn't uploaded. A possible solution for this is to turn portions of the ClientService into a full background service.

**Comment by dbarretto** [comment]
@amalafrozalam This happens on Android 8 devices, One solution would probably be to convert all services to foreground service(Not recommended by Google). The other solution is to use a job scheduler for running these tasks. 

P.s. I am already using a scheduler to fire up the service, but we may now need to implement the upload logic in the scheduler itself.

Refer this link 
https://developer.android.com/about/versions/oreo/android-8.0-changes

**Comment by amalafrozalam** [comment]
@dbarretto yeah I think we should implement the logic into the scheduler then. For any network I/O we should do this, just to be on the safe side as well.
