### ISSUE TITLE
BackupCloud Service attempts to dismiss a null dialog

### ISSUE THREAD

**Issue by AmbujPandey** [Intelehealth/Android-Mobile-Client#504]
App crashing on "BackupCloud.java line 125"
Originator- Ambuj Pandey
Status- OPEN
Checked from- July 19,2018
Bug type- Coding error

**Environment:**
Mobile Brand- Xiomi 
Model- Redmi 4
OS Version- 7.1.2
App Version- 1.3.3
Started- July 26th, 2018
lasst crash date July 27, 2018
Number of Crashes: 4
User Affected- 1

**Summary:** Fatal Exception: java.lang.NullPointerException
**Description:**
Attempt to invoke virtual method 'void android.app.Dialog.dismiss()' on a null object reference
io.intelehealth.client.activities.home_activity.BackupCloud.startCloudBackup (BackupCloud.java:125)
This crash happen when automatic backup happen at night 10:00 PM. On 10:00 backup method call and backup uploaded to cloud, but it fire the same method 4-5 times in 2 minute interval and every time database update the new db on cloud. During hte firing the same method many times IT CRASHED.

**Steps to Reproduce:** the application have to fire the backup method only once please don't put the method in queue
**Expected Result:** Hit the server only once to upload db.
**Actual Result:** It fire query many times with the interval of 2 minute.

**URL:** [click_here](https://console.firebase.google.com/u/0/project/mobile-crashlytics/crashlytics/app/android:io.intelehealth.client/issues/5b5a4d136007d59fcdde87b0?time=1531958400000:1533859199000&sessionId=5B5A03CB0228000116E5F294D0BBE20B_DNE_0_v2)

**Comment by amalafrozalam** [comment]
The solution for this is very simple. Everywhere in this file where it says dialog.dismiss() just needs a null check to ensure that dialog is not null.

if (dialog != null) { dialog.dismiss() }

**Comment by amalafrozalam** [comment]
Actually, this is related to #505 

If the solution [suggested here](https://github.com/Intelehealth/Android-Mobile-Client/issues/505#issuecomment-414515615) is implemented, then these will need to change accordingly.

**Comment by nehagoel2** [comment]
"This crash happen when automatic backup happen at night 10:00 PM. On 10:00 backup method call and backup uploaded to cloud, but it fire the same method 4-5 times in 2 minute interval and every time database update the new db on cloud. During hte firing the same method many times IT CRASHED." - Not correct
