### ISSUE TITLE
Crashing BUG: App crashing on "LocalRecordsDatabaseHelper.java line 157"

### ISSUE THREAD

**Issue by AmbujPandey** [Intelehealth/Android-Mobile-Client#506]
App crashing on "LocalRecordsDatabaseHelper.java line 157"
Originator- Ambuj Pandey
Status- OPEN
Checked from- July 19,2018
Bug type- Coding error

**Environment:**
Mobile Brand- LGE, Mototrola
Model-  Nexus 5, Moto E (4) Plus
OS Version- 6.0.1, 7.1.1
App Version- 1.2.3, 
Started- July 5th, 2018
last crash date July 21, 2018
Number of Crashes: 3
User Affected- 2

**Summary:** Fatal Exception: java.lang.IllegalStateException

**Description:** Unable to start activity ComponentInfo{io.intelehealth.client/io.intelehealth.client.activities.search_patient_activity.SearchPatientActivity}: android.database.sqlite.SQLiteException: table image_records already exists (code 1): , while compiling: CREATE TABLE image_records(_id integer PRIMARY KEY AUTOINCREMENT,patient_id integer NOT NULL,visit_id integer(10),image_path TEXT NOT NULL,image_type TEXT NOT NULL,parse_id TEXT,delete_status integer NOT NULL)

**Caused by android.database.sqlite.SQLiteException**  table image_records already exists (code 1): , while compiling: CREATE TABLE image_records(_id integer PRIMARY KEY AUTOINCREMENT,patient_id integer NOT NULL,visit_id integer(10),image_path TEXT NOT NULL,image_type TEXT NOT NULL,parse_id TEXT,delete_status integer NOT NULL)

io.intelehealth.client.database.LocalRecordsDatabaseHelper.onCreate (LocalRecordsDatabaseHelper.java:157)

**URL:** [click_here](https://console.firebase.google.com/u/0/project/mobile-crashlytics/crashlytics/app/android:io.intelehealth.client/issues/5b3dd4b16007d59fcdaaeb2e?time=1531958400000:1533859199000&sessionId=5B52D5D4003300016776C4DF9466DE3B_DNE_0_v2)

**Comment by AmbujPandey** [comment]
This crash happens when we are trying to restore the locally .db files when the app is started.

**Comment by amalafrozalam** [comment]
This has already been fixed. This particular device needs to update to the latest version of the app. Version 1.3.3 solves this issue by adding "IF NOT EXISTS" to the create table statement.
