### ISSUE TITLE
VisitSummaryActivity tries to access cursor without checking if cursor is empty

### ISSUE THREAD

**Issue by AmbujPandey** [Intelehealth/Android-Mobile-Client#507]
App crashing on "VisitSummaryActivity.java line 1785"
Originator- Ambuj Pandey
Status- OPEN
Checked from- July 19,2018
Bug type- Coding error

**Environment:**
Mobile Brand- Mototrola
Model- Moto E (4) Plus
OS Version- 7.1.1
App Version- 1.3.2, 
crash date July 20, 2018
Number of Crashes: 1
User Affected- 1

**Summary:** Fatal Exception: android.database.CursorIndexOutOfBoundsException

**Description:** Index -1 requested, with a size of 1310
io.intelehealth.client.activities.visit_summary_activity.VisitSummaryActivity.handleMessage (VisitSummaryActivity.java:1785)

**URL:** [click_here](https://console.firebase.google.com/u/0/project/mobile-crashlytics/crashlytics/app/android:io.intelehealth.client/issues/5b51a21d6007d59fcd24c6a5?time=1531958400000:1533859199000&sessionId=5B519B2101590001349BDBD895904224_DNE_0_v2)

**Comment by amalafrozalam** [comment]
Before attempting to access the cursor on line 1785, the app needs to validate that there is even anything _in_ the cursor. The appropriate code is a while loop:

`while(cursor.moveToNext()){
// int dbConceptID = blah blah
}
`

A while loop or something that looks like the above should do the trick.
