### ISSUE TITLE
App tries to download a null image

### ISSUE THREAD

**Issue by AmbujPandey** [Intelehealth/Android-Mobile-Client#508]
App crashing on "ImageDownloadService.java line 149"
Originator- Ambuj Pandey
Status- OPEN
Checked from- July 19,2018
Bug type- Coding error

**Environment:**
Mobile Brand- Mototrola
Model- Moto E (4) Plus
OS Version- 7.1.1
App Version- 1.3.2, 
crash date July 19, 2018
Number of Crashes: 1
User Affected- 1

**Summary:** Fatal Exception: java.lang.NullPointerException

**Description:** Attempt to get length of null array
io.intelehealth.client.services.ImageDownloadService$1$1.done (ImageDownloadService.java:149)

**URL:** [click_here](https://console.firebase.google.com/u/0/project/mobile-crashlytics/crashlytics/app/android:io.intelehealth.client/issues/5b509c6d6007d59fcd108fb6?time=1531958400000:1533859199000&sessionId=5B50993F0353000137FA40DDFAE6497D_DNE_0_v2)

**Comment by amalafrozalam** [comment]
Needs a null check on line 141 of ImageDownloadService.java.
