### ISSUE TITLE
Crashing BUG: App crashing on "PhysicalExamActivity.java line 330"

### ISSUE THREAD

**Issue by AmbujPandey** [Intelehealth/Android-Mobile-Client#510]
App crashing on "PhysicalExamActivity.java line 330"
Originator- Ambuj Pandey
Status- OPEN
Checked from- July 19,2018
Bug type- Coding error

**Environment:**
Mobile Brand- Mototrola
Model- Moto E (4) Plus
OS Version- 7.1.1
App Version- 1.3.2, 
crash date July 20, 2018
Number of Crashes: 1
User Affected- 1

**Summary:** Fatal Exception: java.lang.RuntimeException
**Description:** Unable to start activity ComponentInfo{io.intelehealth.client/io.intelehealth.client.activities.physical_exam_activity.PhysicalExamActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'io.intelehealth.client.node.Node io.intelehealth.client.node.PhysicalExam.getExamNode(int)' on a null object reference
**Caused by java.lang.NullPointerException**
Attempt to invoke virtual method 'io.intelehealth.client.node.Node io.intelehealth.client.node.PhysicalExam.getExamNode(int)' on a null object reference
io.intelehealth.client.activities.physical_exam_activity.PhysicalExamActivity$PlaceholderFragment.onCreateView (PhysicalExamActivity.java:330)

**URL:** [click_here](https://console.firebase.google.com/u/0/project/mobile-crashlytics/crashlytics/app/android:io.intelehealth.client/issues/5ac1419136c7b23527487e49?time=1531958400000:1533859199000&sessionId=5B51A21902D900013C79DBD895904224_DNE_0_v2)

**Comment by amalafrozalam** [comment]
This looks like it's being caused by a missing Physical Exam. Might want to give the mind maps a once over to determine if there is an issue there.

**Comment by meerapo** [comment]
The app is Not Crashing at all during debug for this error.
