### ISSUE TITLE
Improve the format of prescription to make it more patient-friendly

### ISSUE THREAD

**Issue by vibhabhirud** [Intelehealth/Android-Mobile-Client#514]
Medication should be in easy format eg. morning, afternoon, evening 1-0-1. May require OpenMRS changes @nehagoel2 need your inputs.
Put in as much translation as possible- specially headings.
Spacing and overall look to be improved

**Comment by nehagoel2** [comment]
General changes:
1. Add gender
2. Remove occupation
3. Add two <br> after Patient Id and after Chief Complaints

VSO specific changes:
1. Change header
2. Under complaints - all the complaint text
3. Remove Patient History and Family History
