### ISSUE TITLE
"Unable to fetch location" when we use more then 12 character in EditText.

### ISSUE THREAD

**Issue by AmbujPandey** [Intelehealth/Android-Mobile-Client#538]
Whenever we are trying to enter IP/DNS to the URL, this trigger the server to fetch the location on each character(after 11) entered in EditText. When it can't fetch the location successfully, it is showing notification "Unable to fetch location" .
This can be solved by using a button which will fetch location on hitting ok, not on every character.

**Comment by AmbujPandey** [comment]
I added a button ' OK '
- I commented code which fetched the location on every character changed in URL edit text box.
- I put code to fetch for location from server in OK button.
- On every text changed in URL edit text box, location will be empty, user have to again hit OK button.
- I change the Toast msg from 'Unable to fetch location'  to  'Please correct your URL'
- I made a round shape (round by 15dp) button which contain blue background and color change to 
            grey on click button. 
![ok_button](https://user-images.githubusercontent.com/24957597/46667252-b8e91600-cbe6-11e8-9bc7-4e3785cb1f26.png)

**Comment by nehav39** [comment]
Branch: reverted-back (from Quick changes)
