### ISSUE TITLE
Health workers need a way to "flag" complicated cases where they need help

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#549]
Health workers should be able to "star" or "flag" an important case to bring it to the top of the priority list for the doctor.

**Comment by nehagoel2** [comment]
Create a new visit attribute type called "flag" (by default the datatype of a visit attribute is a long varchar).

**Comment by nehagoel2** [comment]
This is a "Nice to have feature" and can be implemented in a later release if there is not enough time to roll it out in this one.

**Comment by kundanmail55** [comment]
1. Create a new encounter type "Flagged".
2. Post request with uuid as 'ca5f5dc3-4f0b-4097-9cae-5cf2eb44a09c'

**Comment by CharanMaddireddy** [comment]
@kundanmail55  as discussed yesterday over call, from android one more encounter will hit to say that this visit is emergency case? Can you provide the input parameters how it should be?

@nehagoel2  and @amalafrozalam  we will be adding one checkbox, above to **upload to doctor button** saying **Emergency**. If Health worker checks it then a new row will be added into the queue table with necessary details + Flagged encounter type.

**Comment by CharanMaddireddy** [comment]
@kranthi-mahiti please move the emergency column to visit table instead of patient table. change the code accordingly.

**Comment by kranthi-mahiti** [comment]
@raunaqp can you explain the steps to reproduce the bug. I am attaching screen shot both encounter and time stamp is different hence it is not an exact duplicate.
![screenshot-demo intelehealth io-2019 03 07-11-21-44](https://user-images.githubusercontent.com/47356810/53935187-647d9000-40cb-11e9-93ac-2b3bd1024b07.png)

**Comment by raunaqp** [comment]
@kranthi-mahiti  In this case, it wasn't a duplicate. But they were flagged as emergency issues, but it wasn't showing as an emergency.
