### ISSUE TITLE
Add pop-up attribute for health messages to emphasize

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#561]
See VSO MNCHN Manuals.

**Comment by nehagoel2** [comment]
The health message needs to be a pop up triggered when a particular node is selected.
This is because the user needs to share the message with the patient before moving on to the next question.

For example:
Q: Do you exclusively breastfeed your child?
A: Yes/No
If No - then share with the mother an educational message about the importance of exclusive breastfeeding. Then move on to the next question.

Suggested solution:

Create a new attribute type called "pop-up". The value of the attribute should be the text which has to be shown in the pop-up. If the text in the pop-up needs to be formatted, then we can insert HTML tags into the text to display the text with proper formatting.

eg of a health message:
<h3> Message for A2 </h3>
<ul>
<li>Breastmilk is adequate for your baby's needs for the <u>first 6 months</u> </li>
<li> Breastfeed starting at birth <i>upto 2 years or beyond</i> </li>
<li> See booklet <b>Family Health Guide pg.3</b> </li>
</ul>

**Comment by amalafrozalam** [comment]
Note, these are all on terminal nodes as of now.
