### ISSUE TITLE
Remove Header from Login & Splash screens

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/Android-Mobile-Client#562]
This is a nice to have

**Comment by AmbujPandey** [comment]
The splash screen doesn't contain Header. 
For  login screen 
![title](https://user-images.githubusercontent.com/24957597/50073560-fa0d3000-01fe-11e9-9015-ec51bf1956ae.png)
Is this ' Intelehealth ' is the title which we have to remove

**Comment by nehagoel2** [comment]
Yes

**Comment by nehav39** [comment]
Branch: reverted-back
