### ISSUE TITLE
Add check to skip activity if no Past Medical History, Family History or Physical Exam files exist

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#565]
Confirm with Vibha if this is a need and that no PMH, FH and PEx are collected for patients.
In any case this is a good check to have.

If no PMH json file exists in the database, skip the Past Medical History Activity AND don't display the PMH card on the Visit Summary screen
If no FH json file exists in the database, skip the Family History Activity AND don't display the FH card on the Visit Summary screen
If no PEx json file exists in the database, skip the Physical Exam activity AND don't display the PEx card on the Visit Summary screen

Estimated time to complete - 4 hours

**Comment by amalafrozalam** [comment]
@meerapo you need to check to see if the file exists. If the file does not exist, you create an intent and start the intent to leave the activity. This needs to happen in the onCreate method of the activity.
