### ISSUE TITLE
Punctuation is different for famHist and patHist maps

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/Android-Mobile-Client#584]
famHist
•Do any of your immediate family members have any of the following diseases? : Allergy: zhs, Asthma, Cancer: zhsn, Cerebrovascular disease, Coronary artery disease, Diabetes Mellitus, Emphysema, Epilepsy/seizure disorder, Peptic ulcer disease, Hepatitis shsb, Hyperlipidemia, Hypertension, Highest BP shsi. Pneumonia, Thyroid disease, Tuberculosis, of zbsj, Category of PTB. Urinary tract infection, Others, zvsbsk..

patHist
• Mode of delivery - Normal, NSBD, Cesaerean. Birth rank - 1st, 2nd, 3rd.
• Allergy: hejs - Asthma - Cancer: - Cerebrovascular disease - Coronary artery disease - Diabetes Mellitus - Emphysema - Epilepsy/seizure disorder - Peptic ulcer disease - Hepatitis shshis - Hyperlipidemia - Hypertension - Highest BP dhjse. Pneumonia - Thyroid disease - Tuberculosis - of bsns shsn, Category of PTB sbsj. Urinary tract infection - Others -sbsk.

**Comment by nehagoel2** [comment]
We want the punctuation for patHist - commas, not dashes
