### ISSUE TITLE
DelayedJobQueueProvider  line 192

### ISSUE THREAD

**Issue by AmbujPandey** [Intelehealth/Android-Mobile-Client#588]
App crashing on "DelayedJobQueueProvider.java line 192"
Originator- Ambuj Pandey
Status- OPEN
Checked from- Nov 14,2018
Bug type- crash

**Environment:**
Mobile Brand- Huawei
Model- ATU-L22,MotoE(4) Plus,
OS Version- 8.0.0,7.1.1
App Version- 1.4,1.3.3
crash date start  Nov 10th, & Sept 3rd 2018
Number of Crashes: 2
User Affected- 2

**Summary:** Fatal Exception: java.lang.IllegalArgumentException            Empty values

**Description:** io.intelehealth.client.database.DelayedJobQueueProvider.update (DelayedJobQueueProvider.java:192)
io.intelehealth.client.services.ClientService.addJobToQueue (ClientService.java:1503)
io.intelehealth.client.services.ClientService.onHandleIntent (ClientService.java:201)

**URL:** [click_here](https://console.firebase.google.com/u/0/project/mobile-crashlytics/crashlytics/app/android:io.intelehealth.client/issues/5adf306a36c7b23527ecd1a7?time=last-seven-days&sessionId=5B8C9CC403E4000128FC2E931410C17A_DNE_0_v2)  Same issue as #516

**Comment by nehagoel2** [comment]
2 more crashes on Feb 3rd

**Comment by kranthi-mahiti** [comment]
This error is not showing. it showing blank
![Screen Shot 2019-03-15 at 4 04 57 PM](https://user-images.githubusercontent.com/47356810/54425745-1e17d900-473c-11e9-8a55-e95d4f3f27bb.png)

**Comment by raunaqp** [comment]
Same as #629
