### ISSUE TITLE
.DB and MySQL file storing different concept ID for same data.

### ISSUE THREAD

**Issue by AmbujPandey** [Intelehealth/Android-Mobile-Client#605]
In .DB file, obs table contains medical advice which is provided by the doctor.
Currently,  advice chain in OpenMRS is in this manner.
Medical advice -> JSV advice -> content/aswers ('Do not walk barefoot','DIET',........)
  163205        ->       163216    ->    163220

In this chain, 
     'Medical advice' is the parent of all remaining.
     'JSV Medication' is the child of 'Medical Advice' and parent of some answers.
     'Content/answer' is the child and actual data.

The problem is .db file is storing the 'concepts/answers' in obs table with **concept ID- 163216**
while openmrs .sql file is storing the 'concepts/answers' in obs table with **concept ID- 163205**

as per my concern, this should be same for store or analyse data.

**Comment by nehav39** [comment]
Branch: reverted-back

**Comment by priyajos** [comment]
Tried to test this scenario as part of the Release 2.0 testing; however as per new code, the doctor prescription/advise (once downloaded into app) does not get stored in Android DB. Hence it is not possible to test the scenario.

**Comment by kundanmail55** [comment]
The concept id is changed to 163205 from android
