### ISSUE TITLE
Mind map server Ip is hard coded in android

### ISSUE THREAD

**Issue by AmbujPandey** [Intelehealth/Android-Mobile-Client#607]
In the android code, Digital ocean mind map server IP is hardcoded in the android code.
We have to change this in the Domain name where app will download mind maps.

**Comment by nehagoel2** [comment]
Replace the hard coded ip to a domain name - mindmaps.intelehealth.io
On our DNS settings I have associated this domain name with the IP address of our mind map server. That way if the ip ever changes we can simply updated the DNS settings.

Note - this is a dirty fix. If another organization wants to host their own deployment of Intelehealth with their own mindmap server, it would be difficult.
The long term fixes could be -
(1) Mind map server IP is a setting that can be set in the config file 
(2) User enters the mind map server IP/URL on the setup screen similar to how they enter the IP/URL name to openMRS
(3) Simply the entire setup process the way CommCare has done with generating a QR code for the person to scan that contains all these configuration settings.
