### ISSUE TITLE
Add language support for Cebuano

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#617]
1. Add translations for all app strings in Cebuano in strings.xml
2. Add Cebuano as a language in Settings > Languages > Current Language

**Comment by vibhabhirud** [comment]
Link to translated Android:
https://docs.google.com/spreadsheets/d/1tyQYBymqWyyNrs4FlvuGl6D_NpV0WgCP0b6UTx3Xj9Y/edit#gid=0
