### ISSUE TITLE
Language support is not working properly in Android 7 and 8

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#618]
Issue observed on devices with Android 7 and higher. 
TODO:
- Test on Android 7 devices
- Test on Android 8 devices

**Comment by nehagoel2** [comment]
May have been fixed for Android 7 devices.

**Comment by kranthi-mahiti** [comment]
Only home page is showing English remaining everything working fine in the app

**Comment by kranthi-mahiti** [comment]
![screenshot_20190226-182744](https://user-images.githubusercontent.com/47356810/53414359-98362700-39f4-11e9-941d-e75f7e345930.png)
![screenshot_20190226-182750](https://user-images.githubusercontent.com/47356810/53414361-98362700-39f4-11e9-846d-170003201afe.png)
![screenshot_20190226-182758](https://user-images.githubusercontent.com/47356810/53414362-98cebd80-39f4-11e9-8d31-6de6db371330.png)
![screenshot_20190226-182802](https://user-images.githubusercontent.com/47356810/53414363-98cebd80-39f4-11e9-87c5-67ad1a85db70.png)
![screenshot_20190226-182814](https://user-images.githubusercontent.com/47356810/53414365-99675400-39f4-11e9-8b91-2d7568718998.png)


this only occurring for android 7 version and android 8 version

**Comment by raunaqp** [comment]
Hey @kranthi0987 could you figure out a reason, why is that the case?
