### ISSUE TITLE
Upgrade app to support Android 7

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#619]

**Comment by raunaqp** [comment]
Does this involve more testing at first, before fixing the issue? The current version was found to be supported for Android 7.

**Comment by raunaqp** [comment]
@kranthi-mahiti  The app keeps crashing , once I change the settings to Cebuano in the main screen for Android 7.

**Comment by raunaqp** [comment]
The app crashes in the vitals page again! @kranthi0987
