### ISSUE TITLE
Upgrade app to support Android 8

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#620]
Known issues with Android 8:
1. Bug with Job Dispatch service causing app to crash - See issue #625 
2. Notifications are not displaying

**Comment by CharanMaddireddy** [comment]
https://medium.com/@kevalpatel2106/how-to-handle-background-services-in-android-o-f96783e65268

@kranthi-mahiti Please refer above link and below is the piece of code to be added in JobDispatchService.java by replace startService method.

                  if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O)
                    {
                        startForegroundService(serviceIntent);
                    } else {
                        startService(serviceIntent);
                    }

**Comment by kranthi-mahiti** [comment]
@raunaqp - i have done a fix for this.Please test this issue on android 8 and close if resolved.Changes are already present in the apk that was sent on friday

**Comment by nehagoel2** [comment]
1. Would have been better to use shared preferences to handle this instead of loading the config file on Visit Summary for temp values
2. These commits may have fixed #656 - please check
