### ISSUE TITLE
JobDispatchService.java line 127

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#625]
Known issue on Android 8 and higher

[Firebase crashlytics log](https://console.firebase.google.com/u/1/project/mobile-crashlytics/crashlytics/app/android:io.intelehealth.client/issues/5b5687986007d59fcd8af88b?time=last-ninety-days&sessionId=5C5C01C602EC000148E9F1721BDAAECA_DNE_0_v2)

**Comment by CharanMaddireddy** [comment]
We are taking this task under 1.5.2 release

**Comment by raunaqp** [comment]
@kranthi-mahiti  This crash just happened again in my phone with the new version. Can you please check?

**Comment by kranthi-mahiti** [comment]
@raunaqp which i sent apk that doesn't have fix of that crash. if we merge all branches then app has all fixes

**Comment by kranthi-mahiti** [comment]
@raunaqp please retest and close the issue.
