### ISSUE TITLE
HelperMethods.java line 144

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/Android-Mobile-Client#628]
https://console.firebase.google.com/u/1/project/mobile-crashlytics/crashlytics/app/android:io.intelehealth.client/issues/5c57cdfaf8b88c2963955bd9?time=last-thirty-days&sessionId=5C593140016000011FC5DA16D04FA26C_DNE_0_v2

**Comment by kranthi-mahiti** [comment]
This one also not opening
