### ISSUE TITLE
DelayedJobQueueProvider.java line 192

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/Android-Mobile-Client#629]
https://console.firebase.google.com/u/1/project/mobile-crashlytics/crashlytics/app/android:io.intelehealth.client/issues/5adf306a36c7b23527ecd1a7?time=last-thirty-days&sessionId=5C56EA8A00DE000139298D11D1A5140A_DNE_0_v2

**Comment by CharanMaddireddy** [comment]
While updating existing job into the queue the queue ID became empty.  
Can be handled with a condition and try exception code.

**Comment by kranthi-mahiti** [comment]
This one also not opening
