### ISSUE TITLE
VisitSummaryActivity.java line 639

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/Android-Mobile-Client#630]
https://console.firebase.google.com/u/1/project/mobile-crashlytics/crashlytics/app/android:io.intelehealth.client/issues/5c5d2ddcf8b88c296313f809?time=last-thirty-days&sessionId=5C5D2E0C01FB00014B0A950516BF0A4E_DNE_0_v2

**Comment by kranthi-mahiti** [comment]
This one also not opening

**Comment by kranthi-mahiti** [comment]
code place is changed. and it is raised in the 1.4.1
