### ISSUE TITLE
AsyncTask.java line 325

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/Android-Mobile-Client#631]
https://console.firebase.google.com/u/1/project/mobile-crashlytics/crashlytics/app/android:io.intelehealth.client/issues/5ae0195336c7b235270122a0?time=last-thirty-days&sessionId=5C5862C702560001176FB7BC8D76E635_DNE_0_v2

**Comment by kranthi-mahiti** [comment]
This one also not opening
