### ISSUE TITLE
ClientService.java line 915

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/Android-Mobile-Client#634]
https://console.firebase.google.com/u/1/project/mobile-crashlytics/crashlytics/app/android:io.intelehealth.client/issues/5c5d2468f8b88c29631328db?time=last-thirty-days&sessionId=5C5D244700C100011366950516BF0A4E_DNE_0_v2

**Comment by kranthi-mahiti** [comment]
This one also not opening
