### ISSUE TITLE
Restore data from cloud automatically if local backup is not found

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/Android-Mobile-Client#638]
Currently the user has to go to Settings>Restore to restore the back up from the cloud.
If a local backup was not found, the app should automatically fetch the backup from the cloud.

**Comment by raunaqp** [comment]
After version 2.0, cloud back-up feature is handled by sync module.

**Comment by vibhabhirud** [comment]
After version 2.0-beta-1 cloud back up feature is handled by sync module
