### ISSUE TITLE
Node.java line 299

### ISSUE THREAD

**Issue by raunaqp** [Intelehealth/Android-Mobile-Client#656]
https://console.firebase.google.com/u/0/project/mobile-crashlytics/crashlytics/app/android:io.intelehealth.client/issues/5c77b0f5f8b88c2963667b2f?time=last-seven-days&sessionId=5C77C63A005A000133E75A9FCF711259_DNE_0_v2

**Comment by nehagoel2** [comment]
Moved into Release 1.5.2
