### ISSUE TITLE
Visit.Summary.Activity.java Line396

### ISSUE THREAD

**Issue by raunaqp** [Intelehealth/Android-Mobile-Client#663]
https://console.firebase.google.com/project/mobile-crashlytics/crashlytics/app/android:io.intelehealth.client/issues/5c7e238df8b88c2963f46ba9?time=last-hour&sessionId=5C7F73C2038F00013979A90BF7C5C580_DNE_0_v2

**Comment by kranthi-mahiti** [comment]
This Crashes came while development time yesterday..

**Comment by kranthi-mahiti** [comment]
@raunaqp  this occured during  development from my device.Issue no longer occurs
