### ISSUE TITLE
Setup screen not appearing on  uninstalling and re-installing app.

### ISSUE THREAD

**Issue by sajankos** [Intelehealth/Android-Mobile-Client#669]
Steps to reproduce
1) Uninstall the app.
2) Re install the app.
3)Open the app .Instead of setup activity screen to appear , only login screen appears.
4)Go to android->settings->apps.Select intelehealth and clear data.
5) Reopen the app.The setup activity now appears.

Expected behaviour-On uninstalling the app and re-install , the setup Activity screen needs to appear.

**Comment by raunaqp** [comment]
This is an issue I face quite a bit and then it goes away. While installing the file,  there's a setting known as Dual Apps. If you chose that,  the dual app works fine with setup screen.  

What version are you using?

**Comment by nehav39** [comment]
Fixed: 
If you clear app data -> uninstall the app -> reinstall the app ->setup screen
uninstall the app -> reinstall the app -> Login (without clearing app data)
Health workers accidentally uninstall the app then we don't want the setup screen to appear again

**Comment by nehav39** [comment]
Branch name: reverted-back
