### ISSUE TITLE
ApiClient.java line 25

### ISSUE THREAD

**Issue by raunaqp** [Intelehealth/Android-Mobile-Client#676]
https://console.firebase.google.com/u/0/project/mobile-crashlytics/crashlytics/app/android:io.intelehealth.client/issues/5c8f3f2ff8b88c2963858a88?time=last-thirty-days&sessionId=5C948A7E007E000108B79AD7CEE870F5_DNE_0_v2

**Comment by kranthi-mahiti** [comment]
it is also closed in the firebase
