### ISSUE TITLE
PhysicalExamActivity.java line 334

### ISSUE THREAD

**Issue by raunaqp** [Intelehealth/Android-Mobile-Client#677]
https://console.firebase.google.com/u/0/project/mobile-crashlytics/crashlytics/app/android:io.intelehealth.client/issues/5c6fc763f8b88c2963b96188?time=last-seven-days&sessionId=5C948C0B019C00010FD59AD7CEE870F5_DNE_0_v2

**Comment by kranthi-mahiti** [comment]
it is closed in the firebase
