### ISSUE TITLE
The UI of the patient exit feedback is confusing

### ISSUE THREAD

**Issue by vibhabhirud** [Intelehealth/Android-Mobile-Client#690]
1. Current: The 'Submit' and 'Skip' buttons are in dark gray and the text is in black. As a result, the HW is not are to differentiate correctly.
Desired: The colours to be changed to add more contrast Eg. Purple button with white text.

2. Current: The Skip button is above Submit button. So the HW intuitively presses the Skip button, even though she intends to press Submit
Desired: The Skip button is to lower right of the Submit Button in a smaller font.

**Comment by vibhabhirud** [comment]
Meera has already worked on this issue and her worked is committed to the repo. But it has to be reviewed and merged.

**Comment by nehav39** [comment]
Branch name: UI_changes
