### ISSUE TITLE
If a patient has several complaints, some questions get repeated between the complaints - mostly in associated symptoms

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/Android-Mobile-Client#726]
The repeated questions are mainly in the associated symptoms
This may cause frustration for the health worker as well as the patient. However we need to more closely look at how repeated questions could be removed when across symptoms

Proposed solution: Create a new activity for Associated symptoms.
In the Question Node activity, all the symptom related questions are asked, except for associated symptoms. The associated symptoms are asked on the newly created associated symptom activity.
If a patient has more than one complaint, then the associated symptoms list for both the complaints are compared, the duplicate associated symptoms are removed and a list of associated symptoms (without duplicates) are shown in the new associated symptoms activity

**Comment by amalafrozalam** [comment]
The physical exam activity creates a mind map dynamically based on the complaints selected; this patient-specific mindmap is a subset of the nodes from the larger Physical Exams mindmap. 

Similar process should be done for the associated symptoms, creating a mind map dynamically and ensuring that repeated questions are skipped.

This also assumes that "Associated Symptoms" questions will have sub-nodes for Yes or No answer choices.

**Comment by SagarS23** [comment]
Estimated time : 32 Hrs

**Comment by nehav39** [comment]
Dr. Acharya:
Alternative flow:
Select complaints -> Ans ques about complaint 1 + associated symptoms of complaint 2 -> Ans questions about complaint 2 + associated symptoms of complaint 1 - repeated associated symptoms in complaint 1 -> Fam Hist -> Pat Hist -> Physical Exams
