### ISSUE TITLE
Make HxGuide into a digital assistant with personality

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/Android-Mobile-Client#733]
Update all the documentation accordingly

**Comment by SagarS23** [comment]
How about "Doctroo" or "Prescripta" ?

**Comment by nehav39** [comment]
https://docs.google.com/presentation/d/1rnBAXkll5Ewx0sF_k6OT-vuvab7z-gFrTwtFutemHlU/edit#slide=id.p

**Comment by nehav39** [comment]
By popular vote, HxGuide has now been renamed to Ayu!
