### ISSUE TITLE
HWs need to get a notification for the patients where the doctor has provided the prescription

### ISSUE THREAD

**Issue by raunaqp** [Intelehealth/Android-Mobile-Client#744]
Changes to be made to the:
1- Patient Detail screen - Add Prescription icon on the patient information card , next to the "Active" tag. 
2 - Active Visit screen - Add Prescription icon next to the patient name in the list view
3- Visit Summary screen - Add Prescription icon
When no prescription is given - its in the grayed out state, when its given the icon is in green
When a Visit Complete encounter is created, then the prescription icon is green, if there is no Visit Complete encounter (encounter type 14) then the icon should remain in the disabled state. 
4 - Notification when Visit Complete encounter is created. Text of the notification - "A Doctor's Visit Note has been provided for [Patient Name]", on clicking on the notification, it should go to the visit summary screen for that patient visit where the teleconsultation was given.
If the visit type is not a teleconsultation visit, then the icon should not be seen at all (related to another issue of teleconsultation and non-teleconsultation visit types)

Link to prescription icon:
https://thenounproject.com/search/?q=prescription&i=241239

**Comment by nehav39** [comment]
**How the app will get a notification:** 
The app syncs with the backend server through the middleware every 15 mins and gets the new encounters and obs
When the app downloads the new encounters from the server through the PullDataAPI of the middleware, if the encounters downloaded are of type Visit Note and inserted in the SQLite database then a notification should be shown to the health worker.

There is no need to use a different API or Firebase

**Comment by nehav39** [comment]
Loop on the array list of encounter_list looking for Visit Note encounter_type using the encounter_type_uuid during the Sync.
