### ISSUE TITLE
json file missing while cloning the project into my android studio

### ISSUE THREAD

**Issue by taduvai35** [Intelehealth/Android-Mobile-Client#755]
File google-services.json is missing. The Google Services Plugin cannot function without it. 
 Searched Location: 
E:\Github\Android-Mobile-Client\app\src\nullnull\debug\google-services.json
E:\Github\Android-Mobile-Client\app\src\debug\nullnull\google-services.json
E:\Github\Android-Mobile-Client\app\src\nullnull\google-services.json
E:\Github\Android-Mobile-Client\app\src\debug\google-services.json
E:\Github\Android-Mobile-Client\app\src\nullnullDebug\google-services.json
E:\Github\Android-Mobile-Client\app\google-services.json

**Comment by nehav39** [comment]
Hi @taduvai35
The google-services.json file is an API key for firebase crash reporting.
You should be able to create your own firebase project (see how here https://support.google.com/firebase/answer/9326094)
And generate a file. See how here https://support.google.com/firebase/answer/7015592?hl=en#android

Then add it to the project. That way you have access to crashlytics reporting and other firebase related functionality.

Let me know if this worked for you.
