### ISSUE TITLE
Problems when editing text - in all nodes

### ISSUE THREAD

**Issue by Sidintelehealth** [Intelehealth/Android-Mobile-Client#762]
First observed - Duplication of bp readings coming from physical examination section of the app

When we move towards the physical exam section of the app for hypertension screening protocol and add bp reading -> remove it -> add another reading instead of previous readings -> go to visit summary -> In the on examination section, you see the previous and updated bp readings being displayed.

![Screenshot_20191011-123217(1).png](https://images.zenhubusercontent.com/5d9339bca1bdb00001e54c16/4c6fe0d2-5b91-4086-95fc-6c82adf607a5)

**Comment by nehav39** [comment]
Branch name: https://github.com/Intelehealth/Android-Mobile-Client/tree/Issue-762_Fixed
