### ISSUE TITLE
Mobile app error "Unable to fetch locations"

### ISSUE THREAD

**Issue by giangduong** [Intelehealth/Android-Mobile-Client#792]
I did install and setup a platform follow this link - https://intelehealthwiki.atlassian.net/wiki/spaces/INTELEHEAL/pages/1081574/Technologies+used. However, i got this error "Unable to fetch locations" when setting up the mobile app. The URL of the server is example.domain/openmrs.

The demo URL (demo.intelehealth.io) is working fine. How do you setup this platform server for the mobile app?

Please let me know what is the correct URL of my local server?

Notes:
- The middle ware URI is at /EMR-Middleware/
- I did not install the webapp yet.

**Comment by prithi69** [comment]
1. Make sure that you are on the same internet connection.
2. You need to install the web app first, as because from the web app only through API app use to fetch the location.
3. After installing the web app successfully, you need to put a URL like demo.intelehealth.io:8080.
